In [1]:
import os, pathlib
import pandas as pd
import numpy as np

In [2]:
train_path = "../data/train.csv"
test_path = "../data/test.csv"
laws_de_path = "../data/laws_de.csv"
val_path = "../data/val.csv"
court_consdr = "../data/court_considerations.csv"

In [3]:
train = pd.read_csv(train_path)
val = pd.read_csv(val_path)
law = pd.read_csv(laws_de_path)
court = pd.read_csv(court_consdr)

In [4]:
train.shape

(1139, 3)

In [5]:
law.shape

(175933, 3)

In [6]:
# Get all unique citation from training set
all_train_citation = set()
for citation in train["gold_citations"]  :
    all_train_citation.update(citation.split(";"))

print(f"total unique citation in train citation {all_train_citation}")
print(f"total len of unique citation in all_train_citation = {len(all_train_citation)}")

# check how many of these in law citations
law_citation = set(law["citation"].unique())
overlap_law = all_train_citation.intersection(law_citation)

#check how many of these in court citations
court_citation = set(court["citation"].unique())
overlap_court = all_train_citation.intersection(court_citation)

print(f"overlap with law citation = {overlap_law}")
print(f"len of the overlap citation = {len(overlap_law)}")

print(f"overlap with court citation = {overlap_court}")
print(f"len of the overlap citation = {len(overlap_court)}")

total unique citation in train citation {'Art. 651 Abs. 1 ZGB', 'Art. 31 Abs. 1 GSchG', 'Art. 204 Abs. 1 ZGB', 'Art. 18 BankG', 'Art. 18b DBG', 'Art. 36 BV', 'Art. 236 ZPO', 'Art. 94 Abs. 1 GBV', 'Art. 77 Abs. 1 OR', 'Art. 86a ZGB', 'Art. 49 Abs. 1 BV', 'Art. 155 IPRG', 'Art. 285 Abs. 2 ZGB', 'Art. 14 Abs. 2 FIDLEG', 'Art. 216 Abs. 1 ZGB', 'Art. 78 Abs. 2 BV', 'Art. 93 Abs. 2 BV', 'Art. 42 BV', 'Art. 36 Abs. 1 FIDLEG', 'Art. 13 Abs. 1 BV', 'Art. 169 ZPO', 'Art. 530 Abs. 1 OR', 'Art. 29 Abs. 5 BEG', 'Art. 824 Abs. 2 ZGB', 'Art. 366 ZGB', 'Art. 46a VwVG', 'Art. 20 IPRG', 'Art. 216 Abs. 2 ZGB', 'Art. 40 Abs. 3 RPV', 'Art. 98 Abs. 3 GBV', 'Art. 482 ZGB', 'Art. 24b Abs. 2 RPG', 'Art. 9 Abs. 1 KGTG', 'Art. 181 IPRG', 'Art. 11 Abs. 1 UVG', 'Art. 74a Abs. 2 IRSG', 'Art. 9 Abs. 2 UVG', 'Art. 36 FIDLEG', 'Art. 80 Abs. 4 GBV', 'Art. 145 Abs. 1 ZPO', 'Art. 45a Abs. 3 IPRG', 'Art. 224 Abs. 1 ZPO', 'Art. 9 RAG', 'Art. 81 Abs. 2 BVG', 'Art. 349a Abs. 2 OR', 'Art. 7 Abs. 2 RAG', 'Art. 126 FinfraV', 'Art. 300 Abs. 1 StPO', 'Art. 860 Abs. 2 ZGB', 'Art. 647a ZGB', 'Art. 64 IPRG', 'Art. 12 URG', 'Art. 181 DBG', 'Art. 340b Abs. 3 OR', 'Art. 114 Abs. 3 BV', 'Art. 85 ZPO', 'BGE 126 III 10 E. 2b', 'Art. 307 Abs. 1 StPO', 'Art. 681a Abs. 2 ZGB', 'Art. 47 EleG', 'Art. 118 OR', 'Art. 55 Abs. 1 IPRG', 'Art. 343 Abs. 2 StPO', 'Art. 86 Abs. 2 IPRG', 'Art. 11 Abs. 1 OR', 'Art. 26 Abs. 3 IRSV', 'Art. 29 GSchG', 'Art. 1 Abs. 1 LugÜ', 'Art. 239 StGB', 'Art. 203 OR', 'Art. 15 Abs. 2 StromVG', 'Art. 98 BGG', 'Art. 956a ZGB', 'Art. 116 Abs. 3 BV', 'Art. 50 OR', 'Art. 12 JStPO', 'Art. 11a Abs. 2 DSG', 'Art. 18a DSG', 'Art. 6 Abs. 1 GSchG', 'Art. 309 ZPO', 'Art. 83 IPRG', 'Art. 76 Abs. 2 StGB', 'Art. 491 Abs. 2 ZGB', 'Art. 443 ZGB', 'Art. 85 Abs. 1 ZPO', 'Art. 219 ZPO', 'Art. 30 Abs. 2 DBG', 'Art. 54 AsylG', 'Art. 79 GBV', 'Art. 78 Abs. 5 BV', 'Art. 45a Abs. 1 IPRG', 'Art. 754 Abs. 1 OR', 'Art. 152 Abs. 1 ZPO', 'Art. 10 Abs. 2 BV', 'Art. 221 Abs. 1 StPO', 'Art. 265a SchKG', 'Art. 294 Abs. 2 StGB', 'Art. 14 BV', 'Art. 779a Abs. 1 ZGB', 'Art. 164 ZPO', 'Art. 101 Abs. 3 GBV', 'Art. 5 MSchG', 'Art. 175 DBG', 'Art. 4 WaG', 'Art. 779b Abs. 2 ZGB', 'Art. 68 Abs. 2 GBV', 'Art. 965 Abs. 3 ZGB', 'Art. 189 Abs. 4 BV', 'Art. 80 ZGB', 'Art. 776 Abs. 2 ZGB', 'Art. 52 FINIG', 'Art. 965 Abs. 2 ZGB', 'Art. 13 Abs. 3 URG', 'Art. 93 SchKG', 'BGE 132 III 564 E. 6.2', 'Art. 8 Abs. 3 AsylG', 'Art. 389 ZGB', 'Art. 16 JStPO', 'Art. 41 Abs. 2 OR', 'Art. 32 Abs. 2 FINMAG', 'Art. 97 Abs. 2 SchKG', 'Art. 10a Abs. 3 USG', 'Art. 113 Abs. 3 BV', 'Art. 18 Abs. 1 BankG', 'Art. 118 Abs. 1 OR', 'Art. 78 Abs. 1 SchKG', 'Art. 181 Abs. 3 DBG', 'Art. 37 Abs. 1 RPV', 'Art. 79 Abs. 1 ZPO', 'Art. 12 Abs. 3 BüG', 'Art. 43 AsylG', 'Art. 857 Abs. 1 ZGB', 'Art. 29 Abs. 2 BV', 'Art. 30 Abs. 1 BV', 'Art. 58 Abs. 1 SVG', 'Art. 862 Abs. 2 ZGB', 'Art. 176 Abs. 1 OR', 'Art. 69 DBG', 'Art. 17 Abs. 2 SchKG', 'Art. 730 Abs. 1 ZGB', 'Art. 263 StGB', 'Art. 237 ZPO', 'Art. 462 Abs. 2 OR', 'Art. 35 FINMAG', 'Art. 222 ZGB', 'Art. 3 DesG', 'Art. 685b Abs. 2 OR', 'Art. 681a Abs. 1 ZGB', 'Art. 61 AsylG', 'Art. 27 Abs. 4 AVIG', 'Art. 59 Abs. 1 LugÜ', 'Art. 356b OR', 'Art. 712m Abs. 1 ZGB', 'Art. 181 Abs. 1 DBG', 'Art. 47 Abs. 2 SVG', 'Art. 529 ZGB', 'Art. 69 Abs. 2 SchKG', 'Art. 46 Abs. 2 BGG', 'Art. 62 Abs. 1 KVG', 'Art. 139 Abs. 1 GBV', 'Art. 45a Abs. 2 IPRG', 'Art. 24 OR', 'Art. 22 Abs. 1 USG', 'Art. 844 Abs. 1 ZGB', 'Art. 185 Abs. 3 BV', 'Art. 23 Abs. 5 GBV', 'Art. 25 Abs. 3 FIDLEG', 'Art. 74 Abs. 1 SchKG', 'Art. 10 Abs. 2 AHVG', 'Art. 395 Abs. 4 ZGB', 'Art. 26 Abs. 1 GBV', 'Art. 143 Abs. 1 ZPO', 'Art. 239 Abs. 2 ZPO', 'Art. 81 Abs. 2 AIG', 'Art. 1085 OR', 'Art. 8 Abs. 1 GSchV', 'Art. 77 ZPO', 'Art. 24c Abs. 5 RPG', 'Art. 42 BüG', 'Art. 37 VGG', 'Art. 2 Abs. 2 AIG', 'Art. 57 ATSG', 'Art. 9 URG', 'Art. 50 Abs. 1 GBV', 'Art. 46 Abs. 2 GBV', 'Art. 9 Abs. 1 URG', 'Art. 498 ZGB', 'Art. 308 ZPO', 'Art. 55 Abs. 2 MSchG', 'Art. 34 Abs. 1 BankV', 'Art. 21 BVG', 'Art. 8 Abs. 1 AsylG', 'Art. 3 RPG', 'Art. 960b Abs. 1 OR', 'Art. 65 Abs. 1 GBV', 'Art. 141 Abs. 2 StPO', 'Art. 646 Abs. 2 ZGB', 'Art. 24b Abs. 1 RPG', 'Art. 9 Abs. 1 DesG', 'Art. 653 Abs. 1 ZGB', 'Art. 67 Abs. 1 URG', 'Art. 964 ZGB', 'Art. 960a Abs. 4 OR', 'Art. 560 Abs. 1 ZGB', 'Art. 56 Abs. 2 StGB', 'Art. 18 Abs. 1 DBG', 'Art. 458 Abs. 2 OR', 'Art. 960e Abs. 4 OR', 'Art. 626 Abs. 1 ZGB', 'Art. 59 Abs. 4 StGB', 'Art. 16 Abs. 2 GBV', 'Art. 26 BetmG', 'Art. 23 ZGB', 'Art. 30 Abs. 1 BüV', 'Art. 245 Abs. 1 ZPO', 'Art. 65 Abs. 2 IPRG', 'Art. 223 Abs. 2 ZPO', 'Art. 13 Abs. 2 BV', 'Art. 860 Abs. 1 ZGB', 'Art. 32 Abs. 1 FINMAG', 'Art. 34 Abs. 1 StGB', 'Art. 70 Abs. 2 IRSG', 'Art. 3 Abs. 2 FIDLEV', 'Art. 358 OR', 'Art. 3 Abs. 6 FIDLEV', 'Art. 62 Abs. 2 AIG', 'Art. 9 BüG', 'Art. 48 Abs. 1 VwVG', 'Art. 39 Abs. 1 BV', 'Art. 28 URG', 'Art. 356 Abs. 4 StPO', 'Art. 343 StPO', 'Art. 647e Abs. 2 ZGB', 'Art. 12 Abs. 3 StGB', 'Art. 8 Abs. 1 BGFA', 'Art. 28 JStG', 'Art. 634 ZGB', 'Art. 42 Abs. 1 JStPO', 'Art. 54 Abs. 4 GBV', 'Art. 973d OR', 'Art. 468 Abs. 1 ZGB', 'Art. 26 HMG', 'Art. 501 Abs. 2 ZGB', 'Art. 2 Abs. 4 PrSG', 'Art. 7 Abs. 2 IRSG', 'Art. 212 Abs. 1 ZPO', 'Art. 19 Abs. 2 FamZG', 'Art. 49 OR', 'Art. 197 Abs. 2 ZGB', 'Art. 2 Abs. 1 BEG', 'Art. 166 Abs. 1 IPRG', 'Art. 333 Abs. 1 StGB', 'Art. 221 ZGB', 'Art. 91 Abs. 3 GBV', 'Art. 681a ZGB', 'Art. 131 Abs. 2 OR', 'Art. 36 PatG', 'Art. 42 Abs. 2 FINMAG', 'Art. 1a MVG', 'Art. 4 DesG', 'Art. 12 ZGB', 'Art. 97 Abs. 1 SchKG', 'Art. 72 Abs. 1 BV', 'Art. 13 Abs. 1 MSchG', 'Art. 137 Abs. 5 WRV', 'Art. 66a Abs. 1 StGB', 'Art. 27 FinfraG', 'Art. 182 ZGB', 'Art. 151 Abs. 1 FinfraG', 'Art. 247 Abs. 3 StPO', 'Art. 130 Abs. 1 ZPO', 'Art. 51 ATSG', 'Art. 198 ZPO', 'Art. 65a Abs. 1 IRSG', 'Art. 7 Abs. 7 USG', 'Art. 684 Abs. 2 ZGB', 'Art. 116 Abs. 1 StPO', 'Art. 26 BankG', 'Art. 295 ZPO', 'Art. 29 Abs. 2 URG', 'Art. 86 ZPO', 'Art. 277 Abs. 1 ZGB', 'Art. 91 Abs. 1 UVG', 'Art. 864 ZGB', 'Art. 37 Abs. 1 BV', 'Art. 745 Abs. 1 ZGB', 'Art. 6 Abs. 1 BankV', 'Art. 64 Abs. 1 GBV', 'Art. 24 LugÜ', 'Art. 59 StGB', 'Art. 55 Abs. 4 MSchG', 'Art. 967 OR', 'Art. 28 IVG', 'Art. 970 Abs. 2 ZGB', 'Art. 197 Abs. 1 StPO', 'Art. 16 Abs. 3 DBG', 'Art. 354 StPO', 'Art. 2 Abs. 5 KGTG', 'Art. 87 Abs. 2 GBV', 'Art. 706 Abs. 2 OR', 'Art. 80p IRSG', 'Art. 285a StPO', 'Art. 336 Abs. 1 OR', 'Art. 390 Abs. 3 ZGB', 'Art. 488 Abs. 2 ZGB', 'Art. 41 OR', 'Art. 63 Abs. 3 KOV', 'Art. 101 OR', 'Art. 145 Abs. 2 ZPO', 'Art. 31 Abs. 1 JStPO', 'Art. 27 Abs. 1 EOG', 'Art. 754 OR', 'Art. 205 Abs. 2 ZGB', 'Art. 33 Abs. 3 OR', 'Art. 2 Abs. 1 KGTG', 'Art. 296 Abs. 2 ZGB', 'Art. 98 Abs. 1 IPRG', 'Art. 10 Abs. 3 BV', 'Art. 712g ZGB', 'Art. 63 Abs. 1 KOV', 'Art. 39 URG', 'Art. 19 Abs. 2 EOG', 'Art. 20a IRSG', 'Art. 35 Abs. 4 SVG', 'Art. 321e OR', 'Art. 58 Abs. 1 FIDLEG', 'Art. 46 GBV', 'Art. 123 Abs. 2 GBV', 'Art. 47 OR', 'Art. 11 VVEA', 'Art. 336c Abs. 1 OR', 'Art. 28 Abs. 1 AHVV', 'Art. 147 StPO', 'Art. 64 GBV', 'Art. 78 Abs. 1 GBV', 'Art. 21 Abs. 2 VStG', 'Art. 5 DBG', 'Art. 25a VwVG', 'Art. 118 StPO', 'Art. 55 AsylG', 'Art. 659 OR', 'Art. 229 Abs. 1 ZPO', 'Art. 22 SchKG', 'Art. 337c Abs. 3 OR', 'Art. 65 Abs. 1 IPRG', 'Art. 26 Abs. 1 JStPO', 'Art. 63 Abs. 2 DBG', 'Art. 965 Abs. 1 ZGB', 'Art. 311 Abs. 1 ZPO', 'Art. 39 Abs. 1 LSV', 'Art. 30 DBG', 'Art. 12 Abs. 2 BankV', 'Art. 58a AIG', 'Art. 27 Abs. 1 SVG', 'Art. 753 Abs. 2 ZGB', 'Art. 205 OR', 'Art. 3 ZGB', 'Art. 712a Abs. 1 ZGB', 'Art. 91a SVG', 'Art. 64 OR', 'Art. 69 Abs. 1 ZPO', 'Art. 80 GBV', 'Art. 716a Abs. 1 OR', 'Art. 234 ZPO', 'BGE 126 III 361 E. 5a', 'Art. 22 Abs. 1 VStG', 'Art. 473 ZGB', 'Art. 14 Abs. 3 FIDLEG', 'Art. 791 Abs. 1 ZGB', 'Art. 8 StPO', 'Art. 321a Abs. 1 OR', 'Art. 5 Abs. 2 KFG', 'Art. 147 Abs. 1 StPO', 'Art. 108 ZPO', 'Art. 9 Abs. 1 SebG', 'Art. 41 Abs. 1 StGB', 'Art. 693 Abs. 2 OR', 'Art. 53 Abs. 2 GBV', 'Art. 301a Abs. 5 ZGB', 'Art. 31 GBV', 'Art. 934 ZGB', 'Art. 20 Abs. 2 USG', 'Art. 216 OR', 'Art. 3 KFG', 'Art. 712h Abs. 1 ZGB', 'Art. 40 Abs. 2 StGB', 'Art. 5 Abs. 1 BV', 'Art. 37 Abs. 2 RPV', 'BGE 132 III 342 E. 2.3.1', 'Art. 3 StAhiG', 'Art. 6 StPO', 'Art. 16 UVG', 'Art. 4 ATSG', 'Art. 254 Abs. 1 ZPO', 'Art. 2 WG', 'Art. 3 BankG', 'Art. 733 ZGB', 'Art. 276 Abs. 2 ZGB', 'Art. 96 IPRG', 'Art. 160 Abs. 1 ZPO', 'Art. 37a RPG', 'Art. 408 ZGB', 'Art. 19 Abs. 2 URG', 'Art. 7 RAG', 'Art. 674 Abs. 2 ZGB', 'Art. 11 Abs. 1 RPG', 'Art. 127 Abs. 3 BV', 'Art. 177 StGB', 'Art. 659 Abs. 2 OR', 'Art. 3 Abs. 5 FIDLEV', 'Art. 10 Abs. 2 DBG', 'Art. 2 Abs. 6 LSV', 'Art. 7 Abs. 1 TwwV', 'Art. 458 Abs. 1 ZGB', 'Art. 52 Abs. 1 FINIG', 'Art. 514 ZGB', 'Art. 3 Abs. 1 JStPO', 'Art. 7 Abs. 2 FINMAG', 'Art. 512 ZGB', 'Art. 8 Abs. 2 EBV', 'Art. 16b EOG', 'Art. 156 FinfraG', 'Art. 839 Abs. 3 ZGB', 'Art. 990 OR', 'Art. 190 Abs. 2 ZPO', 'Art. 56 Abs. 1 ATSG', 'Art. 9 Abs. 3 AVIG', 'Art. 180a Abs. 1 IPRG', 'Art. 34 FINMAG', 'Art. 12 Abs. 1 JStPO', 'BGE 132 III 668 E. 3.2', 'Art. 343 Abs. 3 StPO', 'Art. 64 Abs. 1 LugÜ', 'Art. 475 ZGB', 'Art. 66 ATSG', 'Art. 25 Abs. 1 BV', 'Art. 15 Abs. 1 LSV', 'Art. 9 Abs. 3 UWG', 'Art. 680 Abs. 2 OR', 'Art. 712i Abs. 3 ZGB', 'Art. 123 Abs. 3 GBV', 'Art. 146 Abs. 4 StPO', 'Art. 254 ZPO', 'Art. 34 DSG', 'Art. 17 Abs. 3 FIDLEV', 'Art. 10a Abs. 2 USG', 'Art. 116 Abs. 1 AIG', 'Art. 126 OR', 'Art. 85 Abs. 1 AIG', 'Art. 518 Abs. 1 ZGB', 'Art. 24 RPG', 'Art. 81 GBV', 'Art. 156 ZPO', 'Art. 309 Abs. 1 StPO', 'Art. 168 StPO', 'Art. 247 ZGB', 'Art. 19 FINIV', 'Art. 15 ArG', 'Art. 40e PatG', 'Art. 26 KVG', 'Art. 37 Abs. 1 GwG', 'Art. 655 Abs. 1 ZGB', 'Art. 60 Abs. 1 OR', 'Art. 423 OR', 'Art. 15 Abs. 2 UVG', 'Art. 27 Abs. 5 DSG', 'Art. 973c OR', 'Art. 608 Abs. 2 ZGB', 'Art. 22 Abs. 1 RPG', 'Art. 120 FinfraG', 'Art. 31 DBG', 'Art. 151 FinfraG', 'Art. 217 StPO', 'Art. 34 Abs. 1 JStPO', 'Art. 17 Abs. 4 SchKG', 'Art. 190 StGB', 'Art. 647e ZGB', 'BGE 143 IV 264 E. 2.6', 'BGE 143 IV 145 E. 8.2.3', 'Art. 3 Abs. 3 StPO', 'Art. 62a Abs. 1 StGB', 'Art. 7 Abs. 1 IRSG', 'Art. 6 Abs. 2 BankV', 'Art. 51 ChemG', 'Art. 3 Abs. 3 DBG', 'Art. 83 AIG', 'Art. 3 IPRG', 'Art. 32 Abs. 1 GBV', 'Art. 81 Abs. 3 GBV', 'Art. 960e OR', 'Art. 512 Abs. 2 ZGB', 'Art. 25 IPRG', 'Art. 328 Abs. 1 ZPO', 'Art. 968 ZGB', 'Art. 15 StromVG', 'Art. 712b Abs. 2 ZGB', 'Art. 976a Abs. 1 ZGB', 'Art. 14 IPRG', 'Art. 224 Abs. 1 ZGB', 'Art. 2 Abs. 1 FinfraV', 'Art. 69 Abs. 1 BPR', 'Art. 369 Abs. 1 ZGB', 'Art. 22 Abs. 1 JStG', 'Art. 272 ZGB', 'Art. 65 Abs. 1 VwVG', 'BGE 132 III 564 E. 3.1.2', 'Art. 125 Abs. 2 DBG', 'Art. 10 Abs. 1 VStG', 'Art. 31 Abs. 2 KVG', 'Art. 951 Abs. 2 ZGB', 'Art. 98 IPRG', 'Art. 23 StHG', 'Art. 955 ZGB', 'Art. 81 Abs. 1 GBV', 'Art. 8 AVIG', 'Art. 34 Abs. 5 AIG', 'Art. 362 Abs. 3 ZGB', 'Art. 659a Abs. 2 OR', 'BGE 138 II 300 E. 3.2', 'Art. 50 PatG', 'Art. 64 Abs. 4 StGB', 'Art. 150 Abs. 1 ZPO', 'Art. 325 SchKG', 'Art. 66 PatG', 'Art. 58 DBG', 'Art. 95 Abs. 1 IRSG', 'Art. 3 FINIG', 'Art. 207 Abs. 1 SchKG', 'Art. 26 StGB', 'Art. 217 ZPO', 'Art. 265 SchKG', 'Art. 21 AIG', 'Art. 95 SchKG', 'Art. 19 Abs. 2 BetmG', 'Art. 374 Abs. 2 ZGB', 'Art. 474 ZGB', 'Art. 14 Abs. 1 VVG', 'Art. 27 Abs. 2 ZGB', 'Art. 102 Abs. 2 StGB', 'Art. 531 ZGB', 'Art. 321a Abs. 4 OR', 'Art. 779k Abs. 1 ZGB', 'Art. 63 AIG', 'Art. 248 Abs. 1 StPO', 'Art. 655 Abs. 2 ZGB', 'Art. 15 FIDLEG', 'Art. 86 Abs. 1 BGG', 'Art. 11 PrHG', 'Art. 154 FinfraG', 'Art. 492a Abs. 1 ZGB', 'Art. 208 ZGB', 'Art. 306 Abs. 2 ZGB', 'BGE 142 III 413 E. 2.2.5', 'Art. 76 BGG', 'Art. 154 IPRG', 'Art. 348b OR', 'Art. 482 Abs. 2 ZGB', 'Art. 47 Abs. 2 StGB', 'Art. 494 Abs. 1 ZGB', 'Art. 90 IPRG', 'Art. 15 Abs. 1 LugÜ', 'Art. 6 ZPO', 'BGE 137 III 481 E. 2.1', 'Art. 11 Abs. 1 LSV', 'Art. 37 FIDLEG', 'Art. 2 Abs. 2 ZGB', 'Art. 46 Abs. 1 GBV', 'Art. 201 Abs. 1 OR', 'Art. 28 Abs. 3 BEG', 'Art. 83 Abs. 2 AIG', 'Art. 258 ZPO', 'Art. 195a Abs. 1 ZGB', 'Art. 11 BüG', 'Art. 59 Abs. 3 StGB', 'Art. 69 Abs. 1 GBV', 'Art. 13 Abs. 1 UVV', 'Art. 23 JStG', 'Art. 15 Abs. 3 StromVG', 'Art. 4 GSchG', 'Art. 158 Abs. 1 StGB', 'Art. 83 Abs. 8 AIG', 'Art. 14 Abs. 1 StromVG', 'Art. 27 Abs. 2 JStPO', 'Art. 105 ZGB', 'Art. 65a Abs. 3 IRSG', 'Art. 260 StPO', 'Art. 656 Abs. 2 ZGB', 'Art. 9 JStPO', 'Art. 57 Abs. 3 ZGB', 'Art. 256 Abs. 2 ZPO', 'Art. 29 Abs. 2 JStG', 'Art. 40 Abs. 3 URG', 'Art. 2 GBV', 'Art. 229 Abs. 2 ZPO', 'Art. 22 BV', 'Art. 50 FINMAG', 'Art. 3 Abs. 2 DBG', 'Art. 16a RPG', 'BGE 121 IV 94 E. 1b', 'Art. 296 Abs. 3 ZPO', 'Art. 10 Abs. 1 URG', 'Art. 59 DBG', 'Art. 399 Abs. 1 StPO', 'Art. 659 Abs. 3 OR', 'Art. 728 Abs. 1 ZGB', 'Art. 183 ZPO', 'Art. 3 Abs. 1 KGTG', 'Art. 9 Abs. 2 IPRG', 'Art. 56 Abs. 1 DBG', 'Art. 8a Abs. 1 RPG', 'Art. 9 Abs. 2 DBG', 'Art. 8 DesG', 'Art. 857 Abs. 2 ZGB', 'Art. 90 Abs. 3 SVG', 'Art. 33 Abs. 1 DBG', 'Art. 322d Abs. 2 OR', 'Art. 53 AsylG', 'Art. 25 Abs. 1 IPRG', 'Art. 84 Abs. 1 GBV', 'Art. 37h BankG', 'Art. 1 UVPV', 'Art. 12 DSG', 'Art. 2 SRVG', 'Art. 12 Abs. 2 DSG', 'Art. 126 Abs. 1 ZPO', 'Art. 27 WV', 'Art. 948 Abs. 2 ZGB', 'Art. 43 RPV', 'Art. 55a KVG', 'Art. 509 Abs. 1 ZGB', 'Art. 842 Abs. 2 ZGB', 'Art. 84 Abs. 5 FINIV', 'Art. 698 OR', 'Art. 62 Abs. 1 DBG', 'Art. 17 ArG', 'Art. 360 Abs. 2 ZGB', 'Art. 2 Abs. 3 AIG', 'Art. 41 LFG', 'Art. 27 Abs. 1 DBG', 'Art. 19 Abs. 1 URG', 'Art. 199 Abs. 2 ZPO', 'Art. 185 BV', 'Art. 15 Abs. 1 HKsÜ', 'Art. 426 Abs. 1 ZGB', 'BGE 132 III 564 E. 3.2.2', 'Art. 746 Abs. 1 ZGB', 'Art. 2 Abs. 1 UVPV', 'Art. 970 ZGB', 'Art. 793 Abs. 2 ZGB', 'Art. 7 Abs. 6 USG', 'Art. 199 Abs. 2 ZGB', 'Art. 27 IPRG', 'BGE 127 III 332 E. 2', 'Art. 112 OR', 'Art. 84 Abs. 2 GBV', 'Art. 45 IPRG', 'Art. 647c ZGB', 'Art. 199 Abs. 1 ZGB', 'Art. 20 OR', 'Art. 131 Abs. 2 GBV', 'Art. 10 ATSG', 'Art. 9 Abs. 1 BüG', 'Art. 12 NHG', 'Art. 39 Abs. 1 KVG', 'Art. 52 ATSG', 'Art. 261b Abs. 1 OR', 'Art. 7 VStrR', 'Art. 26 Abs. 2 IRSV', 'Art. 101 KVV', 'Art. 87 Abs. 1 BGG', 'Art. 31 VGG', 'Art. 149 Abs. 2 SchKG', 'Art. 60a GSchG', 'Art. 25a RPG', 'Art. 64 Abs. 2 AHVG', 'Art. 1 OR', 'Art. 79 Abs. 1 BV', 'Art. 239 OR', 'Art. 76 Abs. 1 VVG', 'Art. 745 Abs. 3 ZGB', 'Art. 970 Abs. 1 ZGB', 'Art. 363 Abs. 3 StPO', 'Art. 71 VwVG', 'Art. 779l Abs. 1 ZGB', 'Art. 42 StGB', 'Art. 182 BV', 'Art. 961a ZGB', 'Art. 967 Abs. 2 OR', 'Art. 23 Abs. 1 IPRG', 'Art. 3 URG', 'Art. 9 UWG', 'Art. 7 URG', 'Art. 36a KKG', 'Art. 183 StGB', 'Art. 2 BetmG', 'Art. 82 OR', 'Art. 960 Abs. 1 ZGB', 'Art. 155 FinfraG', 'Art. 10 UVG', 'Art. 474 Abs. 1 ZGB', 'Art. 479 ZGB', 'Art. 61 Abs. 1 KVG', 'Art. 30 Abs. 2 BüV', 'Art. 5 Abs. 1 FIDLEG', 'Art. 31c USG', 'Art. 61 ATSG', 'Art. 10 Abs. 3 URG', 'Art. 63 Abs. 1 VwVG', 'Art. 24 JStG', 'Art. 649a Abs. 2 ZGB', 'Art. 712b Abs. 1 ZGB', 'Art. 201 OR', 'Art. 473 Abs. 3 ZGB', 'Art. 22 EpG', 'Art. 6 Abs. 1 EBG', 'Art. 401 Abs. 2 ZGB', 'Art. 15 BV', 'Art. 59 MSchG', 'Art. 354 Abs. 2 StPO', 'BGE 127 III 73 E. 4a', 'Art. 12 Abs. 1 DSG', 'Art. 30c Abs. 4 BVG', 'Art. 86 IPRG', 'Art. 52 Abs. 2 VwVG', 'Art. 11 StGB', 'Art. 22 JStG', 'Art. 8a Abs. 1 EBG', 'Art. 3 Abs. 2 ZGB', 'Art. 858 Abs. 1 ZGB', 'Art. 79 AIG', 'Art. 352 Abs. 1 StPO', 'Art. 27 Abs. 2 BV', 'Art. 27 Abs. 1 SchKG', 'Art. 20 Abs. 1 VST', 'Art. 189 Abs. 1 ZPO', 'Art. 1 Abs. 2 LugÜ', 'Art. 83 Abs. 7 AIG', 'Art. 11 Abs. 2 USG', 'Art. 9 GwG', 'Art. 37h Abs. 2 BankG', 'Art. 7 Abs. 1 BankG', 'Art. 28 Abs. 3 VStV', 'Art. 350 Abs. 2 StPO', 'Art. 527 Abs. 4 ZGB', 'Art. 308 Abs. 1 ZPO', 'Art. 15 JStG', 'Art. 62 AIG', 'Art. 37 Abs. 1 IRSG', 'Art. 517 ZGB', 'Art. 19 Abs. 3 URG', 'Art. 57 Abs. 1 BV', 'Art. 221 StPO', 'Art. 30 KVG', 'Art. 82 BGG', 'Art. 1000 OR', 'Art. 43b Abs. 2 FINMAG', 'Art. 11 URG', 'Art. 718 OR', 'Art. 125 Abs. 1 GBV', 'Art. 94 GBV', 'Art. 4 Abs. 1 DSG', 'Art. 33 Abs. 1 URG', 'Art. 7 Abs. 2 LSV', 'Art. 949a ZGB', 'Art. 29 Abs. 1 ZPO', 'Art. 66 Abs. 1 ATSG', 'Art. 86 BGG', 'Art. 2 Abs. 2 JStG', 'Art. 22 Abs. 2 GBV', 'Art. 23 BankG', 'Art. 794 Abs. 2 ZGB', 'Art. 20 Abs. 1 FIDLEG', 'Art. 55 Abs. 1 OR', 'Art. 15 RPG', 'Art. 30 Abs. 1 DBG', 'Art. 111 Abs. 1 BGG', 'Art. 27 Abs. 4 DSG', 'Art. 23 VStG', 'Art. 9 Abs. 4 DSG', 'Art. 483 ZGB', 'Art. 20 Abs. 1 DBG', 'Art. 282 StPO', 'Art. 13 KFG', 'Art. 129 Abs. 3 GBV', 'Art. 1 Abs. 2 RPG', 'Art. 9 Abs. 2 DesG', 'Art. 74 Abs. 2 ATSG', 'Art. 66d StGB', 'Art. 86 Abs. 1 StGB', 'Art. 5 VwVG', 'Art. 63 URG', 'Art. 2 Abs. 1 ArG', 'Art. 91 Abs. 1 IPRG', 'Art. 5 LugÜ', 'Art. 10 Abs. 1 UVG', 'Art. 263 Abs. 2 StPO', 'Art. 17 Abs. 1 DBG', 'Art. 197 Abs. 1 StGB', 'Art. 2 Abs. 3 DesG', 'Art. 25 Abs. 2 FIDLEG', 'Art. 10 Abs. 2 StGB', 'Art. 322 Abs. 1 ZGB', 'Art. 32 VGG', 'Art. 12 BV', 'Art. 357b OR', 'Art. 6 Abs. 2 NHG', 'BGE 143 II 283 E. 1.2.4', 'Art. 136 Abs. 1 IPRG', 'Art. 679 Abs. 1 ZGB', 'Art. 328b OR', 'Art. 12 Abs. 1 BüG', 'Art. 112 StGB', 'Art. 734 ZGB', 'Art. 360 ZGB', 'Art. 151 Abs. 1 DBG', 'Art. 712c ZGB', 'Art. 78 Abs. 3 GBV', 'Art. 848 ZGB', 'Art. 51 Abs. 1 ArG', 'Art. 224 Abs. 2 StPO', 'Art. 7 Abs. 3 BüV', 'Art. 75 ZGB', 'Art. 41a USG', 'Art. 14a HMG', 'Art. 18 Abs. 1 NHG', 'Art. 141 Abs. 1 StPO', 'Art. 7 OBV', 'Art. 9 Abs. 1 NBG', 'Art. 49 AIG', 'Art. 501 Abs. 1 ZGB', 'Art. 90 SchKG', 'Art. 46 Abs. 2 OR', 'Art. 83 BGG', 'Art. 85 IPRG', 'Art. 492a ZGB', 'Art. 187 OR', 'Art. 34 Abs. 1 ZPO', 'Art. 19 Abs. 2 StPO', 'Art. 9 Abs. 1 UWG', 'Art. 77 FIDLEG', 'Art. 49 IPRG', 'Art. 2 URG', 'Art. 251 ZPO', 'Art. 14 Abs. 1 VStG', 'Art. 31b AsylG', 'Art. 98 Abs. 1 GBV', 'Art. 679 ZGB', 'Art. 30 Abs. 1 AsylV 1', 'Art. 12 ZPO', 'Art. 38a Abs. 1 RPG', 'Art. 4a KGTG', 'Art. 8 Abs. 3 BankG', 'Art. 1 UVV', 'Art. 229 Abs. 3 ZPO', 'Art. 25 Abs. 3 BV', 'Art. 933 ZGB', 'Art. 63 Abs. 2 SVG', 'Art. 93 Abs. 1 ZPO', 'Art. 100 Abs. 1 AVIG', 'Art. 108 SchKG', 'Art. 213 Abs. 3 ZPO', 'Art. 90 Abs. 1 IPRG', 'Art. 37m BankG', 'Art. 20 Abs. 1 NHG', 'Art. 5 AsylG', 'Art. 22 Abs. 1 GBV', 'Art. 89 Abs. 1 StGB', 'Art. 780 Abs. 3 ZGB', 'Art. 25 Abs. 2 USG', 'Art. 6 Abs. 1 UVG', 'BGE 132 III 321 E. 2.2.1', 'Art. 3 ATSG', 'Art. 4a VStG', 'Art. 47 StGB', 'Art. 58 Abs. 4 SVG', 'Art. 336a Abs. 3 OR', 'Art. 763 OR', 'Art. 97 GBV', 'Art. 8 Abs. 1 StGB', 'Art. 79 StGB', 'Art. 1a AHVG', 'Art. 111 Abs. 2 BGG', 'Art. 35 FIDLEG', 'Art. 513 Abs. 1 ZGB', 'Art. 25 Abs. 1 BankG', 'Art. 65 GBV', 'Art. 17 Abs. 1 JStPO', 'Art. 814 Abs. 3 ZGB', 'Art. 42 Abs. 2 RPV', 'Art. 1011 OR', 'Art. 963 Abs. 1 ZGB', 'Art. 7 KGTG', 'Art. 44 AsylG', 'Art. 6 ATSG', 'Art. 91 Abs. 1 SchKG', 'Art. 36 FINMAG', 'Art. 671 Abs. 1 ZGB', 'Art. 470 ZGB', 'Art. 970 Abs. 3 ZGB', 'Art. 321a OR', 'Art. 84 GBV', 'Art. 38 DesG', 'Art. 116 IPRG', 'Art. 8 Abs. 2 IRSV', 'Art. 25 StGB', 'Art. 119 Abs. 3 ZPO', 'Art. 177 Abs. 1 IPRG', 'Art. 20 Abs. 3 VVG', 'Art. 31 Abs. 4 BV', 'Art. 69 ZGB', 'Art. 83 Abs. 4 AIG', 'Art. 11 TEVG', 'Art. 26 Abs. 4 AsylG', 'Art. 36 DesG', 'Art. 326 Abs. 2 ZPO', 'Art. 396 Abs. 3 OR', 'Art. 70 Abs. 1 StPO', 'Art. 30 Abs. 2 USG', 'Art. 56 VwVG', 'Art. 108 AsylG', 'Art. 208 Abs. 3 OR', 'Art. 40 Abs. 1 RPV', 'Art. 55b Abs. 2 USG', 'Art. 46 Abs. 1 VwVG', 'Art. 81 Abs. 3 BGBB', 'Art. 842 Abs. 1 ZGB', 'Art. 206 ZGB', 'Art. 712l Abs. 2 ZGB', 'Art. 53 NBG', 'Art. 18 JStPO', 'Art. 8 ZGB', 'Art. 1 Abs. 1 PatG', 'Art. 9 ZGB', 'Art. 9 GBV', 'Art. 502 ZGB', 'Art. 90 Abs. 2 SVG', 'Art. 85 Abs. 5 AIG', 'Art. 15 IPRG', 'Art. 199 ZGB', 'Art. 72 VAG', 'Art. 87 Abs. 4 GBV', 'Art. 149c IPRG', 'Art. 197 ZGB', 'Art. 52 Abs. 1 ChemG', 'Art. 298b Abs. 1 StPO', 'Art. 979 OR', 'Art. 93 Abs. 3 BV', 'Art. 49 GBV', 'Art. 123 Abs. 1 BV', 'Art. 29 Abs. 4 ZPO', 'Art. 422 Abs. 1 OR', 'Art. 37 Abs. 3 AIG', 'Art. 655a Abs. 1 ZGB', 'Art. 13 IPRG', 'Art. 127 BV', 'Art. 801 ZGB', 'Art. 19 Abs. 1 BetmG', 'Art. 247 Abs. 2 StPO', 'Art. 2 FIDLEG', 'Art. 13 Abs. 3 FIDLEG', 'Art. 426 ZGB', 'Art. 799 Abs. 1 ZGB', 'Art. 146 Abs. 1 StGB', 'Art. 63 Abs. 1 DBG', 'Art. 7 Abs. 3 FINMAG', 'Art. 24b RPG', 'Art. 7 VAV', 'Art. 725 Abs. 3 OR', 'Art. 25 BankG', 'Art. 814 Abs. 2 ZGB', 'Art. 212 Abs. 3 StPO', 'Art. 121 Abs. 5 BV', 'Art. 9 RPG', 'Art. 681b Abs. 1 ZGB', 'Art. 16 LSV', 'Art. 9 Abs. 1 UVG', 'Art. 14 UVV', 'Art. 3 Abs. 2 StPO', 'Art. 8 Abs. 1 BVG', 'Art. 16 ZPO', 'Art. 647 Abs. 1 ZG', 'Art. 119 StGB', 'Art. 228 Abs. 2 StPO', 'Art. 64 Abs. 4 KVG', 'Art. 8a SchKG', 'Art. 862 Abs. 1 ZGB', 'Art. 17 BV', 'Art. 105 BGG', 'Art. 701 Abs. 1 OR', 'Art. 90 Abs. 1 OR', 'Art. 59 Abs. 2 AIG', 'Art. 5 Abs. 1 BankV', 'Art. 24 UVG', 'Ar

In [7]:
print(len(all_train_citation))

2695

In [8]:
#print(f"Missing citation = {len(all_train_citation) - len(overlap)}")

In [9]:
# Check whether we need chunking strategies or not
law["text_word_count"] = law["text"].apply(lambda x: len(str(x).split()) if pd.notnull(x) else 0)
print(law["text_word_count"].describe())

count    175933.000000
mean         31.924392
std          37.209511
min           1.000000
25%          16.000000
50%          24.000000
75%          37.000000
max        4505.000000
Name: text_word_count, dtype: float64

In [10]:
law.head()

,citation,text,title,text_word_count
0,Art. 1 112,Die Einwohnergemeinde Bern tritt der Schweizer...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...,259
1,Art. 2 112,Die Einwohnergemeinde Bern wird ferner der Sch...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...,35
2,Art. 3 Abs. 1 112,1 Falls die Schweizerische Eidgenossenschaft z...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...,143
3,Art. 3 Abs. 2 112,2 Durch Anlage des neuen Verwaltungsgebäudes a...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...,65
4,Art. 4 Abs. 1 112,1 Die Einwohnergemeinde Bern übernimmt im fern...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...,27

In [11]:
val.head()

,query_id,query,gold_citations
0,val_001,May a court lawfully order a three‑month exten...,Art. 221 Abs. 1 StPO;Art. 140 Abs. 1 StGB;Art....
1,val_002,A claimant holding a national vocational diplo...,Art. 8 Abs. 1 ATSG;Art. 8 Abs. 1 IVG;Art. 17 A...
2,val_003,"A. Rivera, a Peruvian national born in 1994 an...",Art. 29 Abs. 2 BV;Art. 221 Abs. 1 StPO;Art. 39...
3,val_004,"Mr. Dalton, born in 1941 and resident in a sma...",Art. 505 Abs. 1 ZGB;Art. 467 ZGB;Art. 469 Abs....
4,val_005,"A parent, separated from their co-parent since...",Art. 133 Abs. 1 ZGB;Art. 133 Abs. 2 ZGB;Art. 2...

In [12]:
#r"Art\.\s*\d+(?:\s+(?:Abs\.|lit\.|Ziff\.)\s+[a-z0-9]+)*\s+[A-Za-z]+"

In [13]:
train["query"][6]

'Erblasserin E hinterlässt zwei Kinder, Ki und K2, sowie ein Nettovermögen von CHF 500000. Es gilt die gesetzliche Erbfolge. Zu Lebzeiten hat K1 von E CHF 100°000 als Unterstützung zur Gründung seines Unternehmens geschenkt bekommen: K2 hat von E ebenfalls CHF 100°000 ohne Gegenleis- tung erhalten, um sich für sein Freizeitvergnügen einen Oldtimer zu kaufen. E hat K2 zudem aus- drücklich von etwaigen Ausgleichungspflichten befreit. \nSind K1 und K2 zur Ausgleichung verpflichtet? Prüfen Sie alle Voraussetzungen der Ausglei- chungspflicht. Ausführungen zur konkreten Höhe der Ausgleichungspflicht sind nicht erforderlich.'

In [14]:
# Validations query contain the citations
val["query"][2]

'A. Rivera, a Peruvian national born in 1994 and with no prior convictions in the forum state, is accused of having, between 5 March and 9 March 2024, together with three accomplices (B. L., C. M. and D. S.) taken part in a series of offenses including the theft and driving off of delivery vans, forcible entry into a riverside storage unit and the theft of items (notably a replica handgun), the assault of a witness with a metal bar, the discharge of a shot toward the river, and on 9 March 2024 the theft of a further van followed by a high‑speed pursuit in which shots were fired toward law‑enforcement officers; A. Rivera was located in a neighbouring state on 18 March 2024, returned to the prosecuting country on 6 June 2024, interviewed and admitted being present but denied active participation. The authority responsible for ordering coercive measures imposed pretrial detention on several occasions and extended it until 1 December 2024, citing flight and collusion risks based on video footage, witness statements and other material. A. Rivera contests the extension arguing a breach of the right to be heard, a lack of sufficient suspicion (notably because no biological traces of him were found on the alleged weapon or certain stolen items) and an infringement of the presumption of innocence. Was the extension of pretrial detention until 1 December 2024 legally justified with regard to the conditions of 221 Abs. 1 StPO (existence of sufficient suspicion and legitimate risks of flight, collusion or reoffending), was the right to be heard respected, and did the reasoning provided give the accused adequate information to effectively challenge the detention?'

In [15]:
import re
# Extract the citation from the validation query
pattern = r"Art\.\s*\d+(?:\s+(?:Abs\.|lit\.|Ziff\.)\s+[a-z0-9]+)*\s+[A-Za-z]+"

# validation query
val_query = val["query"][0]

print("Testing the Regex on the validation query.....")
extracted_citations = re.findall(pattern, val_query)
print(f"extracted_citations: {extracted_citations}")

print("validation golder citations")
val["gold_citations"][0]

print("search on the law_de text whether it has val query citation or not")
for cite in extracted_citations :
    found = law[law["citation"].str.contains(cite, regex=False, na=False)]
    print(f"The matching string are: {found}")
    print(f"len of total matching value {len(found)}")

Testing the Regex on the validation query.....
extracted_citations: ['Art. 221 Abs. 1 lit. b StPO']
validation golder citations
search on the law_de text whether it has val query citation or not
The matching string are: Empty DataFrame
Columns: [citation, text, title, text_word_count]
Index: []
len of total matching value 0

In [16]:
#law[law["citation"].str.contains(cite, regex=False, na=False)]

validation query contains multiples citations. each row can have contain more than one citations.  
But law_de has don't exactly contain val_query citation. it contain some modification verstion of  
citations.  
We have to focus on this matter. Because base on query we have to extract the citation from the  
law_de and court_considerations.

In [17]:
court.sample(5)

,citation,text
438754,8C_282/2022 E. 1,Das Bundesgericht prüft die Eintretensvorausse...
2110806,8C_846/2011 19.04.2012 E. 2,2.1 Nach Art. 90 BGG ist die Beschwerde zuläss...
1820176,5C.45/2006 15.03.2006 E. C,Gegen diesen Entscheid hat der Berufungskläger...
380929,1C_452/2015 E. 3,Les recourants verseront aux intimés la somme ...
892435,4A_74/2015 E. 3,Le recourant versera à l'intimée une indemnité...

In [18]:
court.sample()["text"][0:1]

1889475    Dieses Urteil wird dem Beschwerdeführer, der S...
Name: text, dtype: object

### Court Considerations

In [19]:
# check the shape of the dataset
print(f"Shape of the dataset: {court.shape}")

# check whether it is required chunking or not
court["word_count"] = court["text"].apply(lambda x: len(str(x).split()) if pd.notnull(x) else 0)

print("Court text word count statistics")
display(court["word_count"].describe())

Shape of the dataset: (2476315, 2)
Court text word count statistics

count    2.476315e+06
mean     1.374033e+02
std      1.994214e+02
min      1.000000e+00
25%      2.700000e+01
50%      7.100000e+01
75%      1.720000e+02
max      1.177100e+04
Name: word_count, dtype: float64

In [20]:
court.head()

,citation,text,word_count
0,BGE 139 I 2 E. 1.12.2011,betr. Verweigerung der Beiladung seien gutzuhe...,12
1,BGE 139 I 2 E. 2,Eventualiter sei die Rückweisung an die Vorins...,112
2,BGE 139 I 2 E. 5.1,"In der Sache ist vorweg zu prüfen, ob der Ents...",65
3,BGE 139 I 2 E. 5.2,Art. 34 Abs. 1 BV gewährleistet in allgemeiner...,39
4,BGE 139 I 2 E. 5.3,Im vorliegenden Fall geht es nicht um die Gült...,42

In [21]:
2.476315e+06

2476315.0

In [22]:
# Check for a specific pattern (e.g., 'BGE') in this small chunk
bge_count = court['citation'].str.contains('BGE', na=False).sum()
print(f"\nNumber of 'BGE' (Leading Decisions) in this chunk: {bge_count}")

Number of 'BGE' (Leading Decisions) in this chunk: 96465

In [23]:
val["query"][0]

'May a court lawfully order a three‑month extension of pre‑trial detention under Art. 221 Abs. 1 lit. b StPO (risk of collusion) consistent with the principle of proportionality when the accused—detained after an alleged late‑night assault and theft of a courier satchel containing, inter alia, €5,600—was remanded by an order dated 18 October 2024 for a maximum period up to 15 January 2025, the prosecutor sought an extension on 10 December 2024 primarily citing a concrete risk that the detainee would influence witnesses or tamper with evidence and a risk of reoffending, while the detainee opposed the extension on the ground that most witnesses have already been interviewed, the investigative steps still pending are essentially technical (phone data extraction, CCTV image analysis, and bank record checks), his release would therefore not jeopardize the inquiry, and the alleged victim has withdrawn the complaint—i.e. does the asserted concrete risk of collusion and considerations of proportionality justify a three‑month prolongation in these circumstances?'

In [24]:
gold_target = "Art. 221 Abs. 1 StPO"

In [25]:
match_ = law[law['citation'] == gold_target]

In [26]:
match_.iloc[0]["citation"]

'Art. 221 Abs. 1 StPO'

In [27]:
val.iloc[0]

query_id                                                    val_001
query             May a court lawfully order a three‑month exten...
gold_citations    Art. 221 Abs. 1 StPO;Art. 140 Abs. 1 StGB;Art....
Name: 0, dtype: object

In [28]:
val.iloc[1]

query_id                                                    val_002
query             A claimant holding a national vocational diplo...
gold_citations    Art. 8 Abs. 1 ATSG;Art. 8 Abs. 1 IVG;Art. 17 A...
Name: 1, dtype: object

In [29]:
stpo = law[law["citation"].str.contains("StPO", na=False, regex=False)]

In [30]:
len(stpo)

1441

In [31]:
stpo[["citation", "text"]].sample(5)

,citation,text
131505,Art. 202 Abs. 3 StPO,3 Bei der Festlegung des Zeitpunkts wird auf d...
131780,Art. 289 Abs. 1 StPO,1 Der Einsatz einer verdeckten Ermittlerin ode...
131245,Art. 106 Abs. 1 StPO,1 Die Partei kann Verfahrenshandlungen nur gül...
131470,Art. 186 Abs. 1 StPO,1 Staatsanwaltschaft und Gerichte können eine ...
131500,Art. 200 StPO,Zur Durchsetzung von Zwangsmassnahmen darf als...

In [32]:
val["query"][1]

'A claimant holding a national vocational diploma in warehouse operations worked intermittently as a storage technician from 10 March to 20 September 2022 and was entered as job-seeking on 1 October 2022. From mid-2021 onwards he has suffered from a chronic allergic respiratory disorder (eosinophilic allergic asthma with nasal/ocular symptoms) with raised IgE to seasonal pollens and household mites; he required inpatient treatment for an acute exacerbation in August 2022. Allergy specialists advised placement in a temperature-controlled, low-dust workplace, yet an occupational pulmonologist’s assessment dated 15 April 2023 concluded the claimant retained full capacity for employment and that the condition was stable. Subsequent brief medical notes from his family doctor (dated 12 February and 3 March 2024) state that he is completely unable to perform his usual duties as a storage technician but could carry out adapted work that excludes exposure to dust, pollens and moulds; in early 2024 he ceased a short-term assignment in a semi-open, dusty yard after clinical worsening. Given these conflicting medical opinions (a specialist finding full work capacity, concise treating-physician incapacity notes and workplace-environment recommendations) and the fact that therapeutic options (e.g. allergen immunotherapy/desensitisation) have not been exhausted, does the insured nevertheless have an entitlement, within the meaning of Art. 17 LAI, to a vocational rehabilitation measure and to invalidity insurance benefits (in particular considering the jurisprudential benchmark of roughly a 20% reduction in earning capacity)?'

In [33]:
val_citation = "Art. 17 LAI"

In [34]:
stpo = law[law["citation"].str.contains("LAI", na=False, regex=False)]

In [35]:
stpo

Empty DataFrame
Columns: [citation, text, title, text_word_count]
Index: []

In [36]:
lai = court[court["citation"].str.contains("LAI", na=False, regex=False)]

In [37]:
lai

Empty DataFrame
Columns: [citation, text, word_count]
Index: []

In [38]:
text = val["query"][0]

pattern = r"Art\.\s*\d+(?:\s+(?:Abs\.|lit\.|Ziff\.)\s+[a-z0-9]+)*\s+[A-Za-z]+"
raw_matches = re.findall(pattern, text)

In [39]:
raw_matches

['Art. 221 Abs. 1 lit. b StPO']

In [40]:
#text = val["query"].apply(lambda x : re.findall(pattern, x))

In [41]:

clean_cit = re.sub(r'\s+lit\.\s+[a-z]+', '', raw_matches[0])
clean_cit = re.sub(r'\s+Ziff\.\s+\d+', '', clean_cit)

In [42]:
clean_cit

'Art. 221 Abs. 1 StPO'

In [43]:
clean_cit.split()

['Art.', '221', 'Abs.', '1', 'StPO']

In [44]:
" ".join(clean_cit.split())

'Art. 221 Abs. 1 StPO'

In [45]:
text = train["query"].apply(lambda x : re.findall(pattern, x))

In [46]:
text

0       []
1       []
2       []
3       []
4       []
        ..
1134    []
1135    []
1136    []
1137    []
1138    []
Name: query, Length: 1139, dtype: object

In [47]:
["string"][0]

'string'

In [48]:
val.sample()

,query_id,query,gold_citations
6,val_007,An heirship claims title to a vintage pocket c...,Art. 98 Abs. 2 IPRG;Art. 100 Abs. 1 IPRG;Art. ...

In [49]:
val["query"].tolist()

['May a court lawfully order a three‑month extension of pre‑trial detention under Art. 221 Abs. 1 lit. b StPO (risk of collusion) consistent with the principle of proportionality when the accused—detained after an alleged late‑night assault and theft of a courier satchel containing, inter alia, €5,600—was remanded by an order dated 18 October 2024 for a maximum period up to 15 January 2025, the prosecutor sought an extension on 10 December 2024 primarily citing a concrete risk that the detainee would influence witnesses or tamper with evidence and a risk of reoffending, while the detainee opposed the extension on the ground that most witnesses have already been interviewed, the investigative steps still pending are essentially technical (phone data extraction, CCTV image analysis, and bank record checks), his release would therefore not jeopardize the inquiry, and the alleged victim has withdrawn the complaint—i.e. does the asserted concrete risk of collusion and considerations of proportionality justify a three‑month prolongation in these circumstances?',
 'A claimant holding a national vocational diploma in warehouse operations worked intermittently as a storage technician from 10 March to 20 September 2022 and was entered as job-seeking on 1 October 2022. From mid-2021 onwards he has suffered from a chronic allergic respiratory disorder (eosinophilic allergic asthma with nasal/ocular symptoms) with raised IgE to seasonal pollens and household mites; he required inpatient treatment for an acute exacerbation in August 2022. Allergy specialists advised placement in a temperature-controlled, low-dust workplace, yet an occupational pulmonologist’s assessment dated 15 April 2023 concluded the claimant retained full capacity for employment and that the condition was stable. Subsequent brief medical notes from his family doctor (dated 12 February and 3 March 2024) state that he is completely unable to perform his usual duties as a storage technician but could carry out adapted work that excludes exposure to dust, pollens and moulds; in early 2024 he ceased a short-term assignment in a semi-open, dusty yard after clinical worsening. Given these conflicting medical opinions (a specialist finding full work capacity, concise treating-physician incapacity notes and workplace-environment recommendations) and the fact that therapeutic options (e.g. allergen immunotherapy/desensitisation) have not been exhausted, does the insured nevertheless have an entitlement, within the meaning of Art. 17 LAI, to a vocational rehabilitation measure and to invalidity insurance benefits (in particular considering the jurisprudential benchmark of roughly a 20% reduction in earning capacity)?',
 'A. Rivera, a Peruvian national born in 1994 and with no prior convictions in the forum state, is accused of having, between 5 March and 9 March 2024, together with three accomplices (B. L., C. M. and D. S.) taken part in a series of offenses including the theft and driving off of delivery vans, forcible entry into a riverside storage unit and the theft of items (notably a replica handgun), the assault of a witness with a metal bar, the discharge of a shot toward the river, and on 9 March 2024 the theft of a further van followed by a high‑speed pursuit in which shots were fired toward law‑enforcement officers; A. Rivera was located in a neighbouring state on 18 March 2024, returned to the prosecuting country on 6 June 2024, interviewed and admitted being present but denied active participation. The authority responsible for ordering coercive measures imposed pretrial detention on several occasions and extended it until 1 December 2024, citing flight and collusion risks based on video footage, witness statements and other material. A. Rivera contests the extension arguing a breach of the right to be heard, a lack of sufficient suspicion (notably because no biological traces of him were found on the alleged weapon or certain stolen items) and an infringement of the presumption of innocence. Was the extension of pretrial detention until 1 December 2024 legally justified with regard to the conditions of 221 Abs. 1 StPO (existence of sufficient suspicion and legitimate risks of flight, collusion or reoffending), was the right to be heard respected, and did the reasoning provided give the accused adequate information to effectively challenge the detention?',
 "Mr. Dalton, born in 1941 and resident in a small lakeside town near Thun, executed a handwritten will on 10 October 1997 stating that he left his entire estate to his partner Ms. Lang and, should she predecease him, to his granddaughters Anna (born 1988) and Bella (born 1991). Mr. Dalton and Ms. Lang died in 2010 in an alpine avalanche; Dalton's surviving half‑siblings and a cousin contest the validity of the 10 October 1997 handwritten instrument, alleging that Dalton did not have sufficient command of German and therefore could not have composed a testamentary text containing legal terms such as bequeath or legatee, so the document does not reflect his true intention. Under the Civil Code, does this handwritten (holographic) will meet the formal requirements (including where there is a suspicion that parts of the text may have been added by a third party), must Dalton's testamentary capacity at the time of drafting be regarded as lacking, and are doubts about the testator's language comprehension or vocabulary alone sufficient to annul or to reinterpret the testamentary dispositions in favour of relatives not named in the will?",
 'A parent, separated from their co-parent since 2008, has not had custody of the two children (primary custody is with the other parent); until March 2020 the parent exercised a longstanding visitation pattern (Wednesday evenings, alternate weekends including overnight stays, and portions of school holidays). In March 2021 the parent was accused of twice engaging in sexually inappropriate touching of a teenage friend of the older child (then 15), was briefly held in custody for four days and is the subject of ongoing criminal proceedings and a forensic psychiatric assessment whose conclusions have not been placed in the family-file; the parent says alcohol was involved and since May 2021 has been in an addiction treatment program with regular testing. The local family welfare office recommends limiting contact to daytime only (no overnight stays) and appointing a supervising guardian for contact; overnight visits were suspended pending review and child support was fixed, while the parent requests reinstatement of overnight stays. In these circumstances (allegations with a sexual element, a history of alcoholism, an absent criminal psychiatric report from the family file and a social welfare report recommended), can the civil judge, applying the duty to act ex officio and the child’s best interests standard, provisionally or permanently restrict the parent’s overnight visitation rights, and what scope of fact-finding and what degree/kinds of evidence are necessary before imposing a definitive (rather than merely provisional) restriction on overnight visits?',
 'On 3 March 2012, homeowners Ms. L and her partner Mr. M asked G, an installer they knew socially who works on domestic heating equipment, to help free of charge with the removal of a household fuel reservoir and its connected burner located in a ground‑floor utility room. G did not have the federal authorization required for certified tank decommissioning, came in the afternoon carrying his professional tools (an angle grinder followed by an oxy‑acetylene torch), made only a visual check that the reservoir seemed empty, left the access hatch open for about 90 minutes without operating any mechanical extraction, and did not perform the specified degassing routine (running an air extractor through a number of extraction cycles). A flame developed inside the reservoir, igniting a fire that caused considerable damage to the property. Can G be held liable for the damage, and if so should liability be based on an obligation comparable to a contract for work and services or on non‑contractual liability arising from a gratuitous act of assistance, and according to which standard of care — the objective standard of Art. 364 Abs. 1 OR, or, if treated as a gratuitous favour, Art. 248 Abs. 1 OR by analogy or Art. 41 OR — should his conduct be judged given that he acted without the required federal certificate, used spark‑producing equipment, relied on the apparent emptiness of the reservoir and failed to use an air extractor?',
 'An heirship claims title to a vintage pocket chronometer known as “The Meridian” that belonged to Ms. Barnes, who died in 2010, and contends the timepiece was never validly donated to her visually impaired partner Mr. Collins despite the existence only of a photocopy of a deed of gift dated May 2006 and signed by Ms. Barnes; in late 2010 Mr. Collins handed the chronometer to his representative Ms. Ortega, who sold it to Eastbridge LLC (sale agreement of 12 November 2010) and Eastbridge LLC in turn sold it to Alpine Trading AG (invoice of 8 November 2010; Alpine took physical delivery in March 2011). The heirs attack the alleged gift on grounds that Ms. Barnes lacked testamentary capacity at the time, that the instrument was actually a donation causa mortis, that the original deed is missing and only a photocopy (whose authenticity is disputed) is produced, that Mr. Collins never had exclusive physical control (he had loaned the chronometer to the City Museum in 2007), and that Mr. Collins’ deposition taken in the United States would be barred under the Dead Man’s Statute (Art. 4519 CPLR). Under the law of the State of New York and subsidiarily under Swiss law: was the inter vivos gift from Ms. Barnes to Mr. Collins valid (i.e. were the required elements of donative intent, transfer/delivery and acceptance satisfied) such that Mr. Collins could validly transfer title and Alpine Trading AG became the owner? Additionally, in Swiss proceedings are the photocopy of the deed and Mr. Collins’ U.S. testimony admissible, and if the gift were found invalid would Alpine Trading AG, as a professional purchaser, be required to return the chronometer for lack of good faith or because of negligence (Art. 934 ZGB; Art. 936 ZGB)?',
 'Has a member of the town council of the Borough of L., who chaired the board of a publicly funded community trust receiving municipal grants, committed disloyal management of public interests by, during 2015–2020, doing the following: awarding the trust’s personnel administration to a private company of which he is a managing partner without disclosing the contract to the trust board and nominating his spouse as the company’s representative; launching and expanding a shared-workspace initiative by independently taking on extra leased premises without board approval and causing the trust to incur unnecessary rents and charges; subcontracting day-to-day operation of the shared workspace to that same company, which billed the trust at an increased hourly rate (raised unilaterally from CHF 120 to CHF 170, where the prior rate had been CHF 120); and arranging favourable subleases and deferred depreciation that harmed the trust’s patrimony (itemised amounts: personnel administration fees CHF 28,900; unnecessary rent CHF 13,240; overbilling shared-workspace CHF 2,750 + CHF 4,100; advantageous subleases CHF 31,200; deferred depreciation CHF 12,900; total retained after write-offs CHF 93,089)? Moreover, does the failure of the indictment to expressly allege the unilateral increase in the hourly charge bar conviction on that precise allegation, and, given that a superior-instance remand has already addressed that point, how must the trial-level authority apply the prior remand directive when deciding the matter?',
 'A divorced custodial parent lives alone with four children born in 1996, 1998, 2001 and 2006. The non-custodial parent is serving a prison sentence overseas of about seven years (release date uncertain), has failed to pay previously-ordered maintenance and is co-owner of a coastal condominium that is currently subject to forced sale; after enforcement costs each co-owner is likely to receive roughly €210,000. The custodial parent relies on unemployment benefits and receives state advances on child maintenance; household and child-related fixed expenses leave only a small disposable income. Can the imprisoned non-custodial parent, despite incarceration and an absence of current earnings, be ordered to pay monthly maintenance of €450 per child until age 15 and €550 per child from age 15 to 25 (index-linked), and can the enforcement authority be directed to freeze the portion of the sale proceeds attributable to that parent as security for future maintenance payments, where the custodial parent instead requested a lump-sum capitalization of future pension entitlements and immediate payment of interest?',
 'A Belize-registered investment vehicle (M) authorized its sole beneficial owner (P) to open and operate a euro account with a private bank in Zurich (Q). P delegated day-to-day portfolio handling to an external adviser (R) who held a power of attorney specifically excluding any authority to make direct disposition transactions; over a series of eight months from January 2010 to August 2012 the bank executed several transfer instructions sent by fax and bearing a signature that appeared indistinguishable from P’s, resulting in cumulative debits of EUR 385,420.50. The account advices were placed on the bank’s “statement-hold” option in accordance with standard contractual terms accepted by M/P, which include a clause requiring a written protest within 30 days under penalty of ratification and a broad risk‑allocation/exculpatory provision relieving the bank except in cases of gross negligence. In 2014 M first challenged those transfers as forged and sought indemnification from Q. Q responds that it verified signatures according to the agreed routine, that gross negligence has not been established, that M failed to submit the prescribed written objection within the 30‑day contractual period, and that the substantive claim has been pleaded in Swiss francs whereas the account and disputed debits are denominated in euros. On these facts, is the bank liable to the account holder for the debits effected on the basis of the allegedly forged faxed orders, having regard to the bank’s duty of care in signature checks, the enforceability and effect of the contractual “statement‑hold”/30‑day protest and exculpatory clauses, and the issue of pleading the claim in the wrong currency?']

In [50]:
val.shape

(10, 3)

In [74]:
def split_by_articles(text: str) -> list[str]:
    pattern = r"(Art\.?\s*\d+[a-zA-Z]*)"
    parts = re.split(pattern, text)
    print(parts)
    print(f"len = {len(parts)}")
    chunks = []
    for i in range(1, len(parts), 2):
        print("start for loop...")
        title = parts[i]
        print(f"tilte: {title}")
        content = parts[i+1] if i+1 < len(parts) else ""
        print(f"content: {content}")
        chunks.append(title + " " + content)

    return chunks if chunks else [text]

In [79]:
split_by_articles(law["text"].loc[84387])

['2 Ins Handelsregister müssen eingetragen werden:a. das Datum der Änderung der Statuten;\nb. die Höhe und die Währung des Aktienkapitals und der darauf geleisteten Einlagen sowie Anzahl, Nennwert und Art der Aktien.']
len = 1

['2 Ins Handelsregister müssen eingetragen werden:a. das Datum der Änderung der Statuten;\nb. die Höhe und die Währung des Aktienkapitals und der darauf geleisteten Einlagen sowie Anzahl, Nennwert und Art der Aktien.']

In [56]:
law["text"].loc[0]

'Die Einwohnergemeinde Bern tritt der Schweizerischen Eidgenossenschaft unentgeltlich als Eigentum ab:a. Das Gebäude des Bundesrathauses im roten Quartier der Stadt Bern, mit Nr. 229 bezeichnet, nebst den in demselben enthaltenen Einrichtungen und Mobilien, welche der Einwohnergemeinde angehören, und unter Vorbehalt der im Artikel 62 von der Einwohnergemeinde reservierten Einrichtungen und Gegenstände;\nb. den zwischen den Seitenflügeln des Bundesrathauses und nördlich von dem Mittelbau desselben befindlichen innern Hof von ungefähr 25 000 Quadratfuss Oberfläche.\n Derselbe wird abgetreten bis zu einer in Verlängerung der Nordfassaden der Seitenflügel gezogenen Linie.\n Der in diesem Hofe befindliche Brunnen verbleibt der Einwohnergemeinde, welche denselben in gutem Zustande erhalten und ohne Genehmigung des Bundesrates an dem jetzigen baulichen Zustand mit Inbegriff der Statuen keine Veränderung vornehmen soll.\n Sie wird den Brunnen wie bis anhin mit Wasser versehen.\n Die Eidgenossenschaft verpflichtet sich, den Fortbestand des Brunnens auf ihrem Eigentum als Dienstbarkeit zu übernehmen.\n Der Brunnen sowie der Zugang zu demselben sollen dem Publikum zum angemessenen Hausgebrauch offenstehen.\nc. Eine Parzelle der sogenannten Vannazhalde von ungefähr 7280 Quadratfuss Oberfläche, auf welcher die Eidgenossenschaft ihr Gewächshaus erstellt hat. Ein Plan über die abgetretene Parzelle wird der Übereinkunft beigelegt.\n Die Schweizerische Eidgenossenschaft übernimmt jedoch die Verpflichtung, im Falle der Erbauung einer Strasse längs der Vannazhalde den in beiliegendem Plan gelb angelegten Abschnitt dieser Parzelle der Einwohnergemeinde zum Zwecke des Strassenbaues unentgeltlich wieder abzutreten.\n In diesem Falle ist der Bundesrat berechtigt, im Interesse der räumlichen Verhältnisse des Gewächshauses die Erstellung einer Stützmauer zu verlangen, deren Kosten alsdann zur einen Hälfte die Eidgenossenschaft und zur andern Hälfte die Einwohnergemeinde zu tragen hat.'

In [1]:
text = "Die Einwohnergemeinde Bern tritt der Schweizerischen Eidgenossenschaft unentgeltlich als Eigentum"
word = text.split()

In [2]:
word

['Die',
 'Einwohnergemeinde',
 'Bern',
 'tritt',
 'der',
 'Schweizerischen',
 'Eidgenossenschaft',
 'unentgeltlich',
 'als',
 'Eigentum']

In [3]:
chunk = " ".join(word)

In [4]:
chunk

'Die Einwohnergemeinde Bern tritt der Schweizerischen Eidgenossenschaft unentgeltlich als Eigentum'

In [15]:
def split_by_paragraph(text: str):
    paragraphs = text.split("\n")
    return [p.strip() for p in paragraphs if p.strip()]

In [ ]:
# import re
# from typing import List

# # Step 1: split by legal markers
# def split_by_articles(text: str) -> List[str]:
#     pattern = r"(Art\.?\s*\d+[a-zA-Z]*)"
#     parts = re.split(pattern, text)

#     chunks = []
#     for i in range(1, len(parts), 2):
#         title = parts[i]
#         content = parts[i+1] if i+1 < len(parts) else ""
#         chunks.append(title + " " + content)

#     return chunks if chunks else [text]

In [17]:
def token_chunk(text, chunk_size=250, overlap=50):
    words = text.split()
    chunks = []

    start = 0
    while start < len(words):
        end = start + chunk_size
        chunk = " ".join(words[start:end])
        chunks.append(chunk)

        start = end - overlap

    return chunks

In [18]:
def hybrid_chunk(text):
    # Try article split
    chunks = split_by_articles(text)

    final_chunks = []

    for chunk in chunks:
        if len(chunk.split()) < 300:
            final_chunks.append(chunk)
        else:
            # fallback to paragraph
            paras = split_by_paragraph(chunk)

            for p in paras:
                if len(p.split()) < 300:
                    final_chunks.append(p)
                else:
                    # final fallback
                    final_chunks.extend(token_chunk(p))

    return final_chunks

In [19]:
def build_chunks(laws_df):
    all_chunks = []

    for _, row in laws_df.iterrows():
        citation = row["citation"]
        title = row.get("title", "")
        text = row["text"]

        chunks = hybrid_chunk(text)

        for i, chunk in enumerate(chunks):
            all_chunks.append({
                "citation": citation,
                "title": title,
                "chunk_id": f"{citation}_{i}",
                "text": chunk
            })

    return all_chunks

In [20]:
build_chunks(laws_df=law)

[{'citation': 'Art. 1 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 1 112_0',
  'text': 'Die Einwohnergemeinde Bern tritt der Schweizerischen Eidgenossenschaft unentgeltlich als Eigentum ab:a. Das Gebäude des Bundesrathauses im roten Quartier der Stadt Bern, mit Nr. 229 bezeichnet, nebst den in demselben enthaltenen Einrichtungen und Mobilien, welche der Einwohnergemeinde angehören, und unter Vorbehalt der im Artikel 62 von der Einwohnergemeinde reservierten Einrichtungen und Gegenstände;\nb. den zwischen den Seitenflügeln des Bundesrathauses und nördlich von dem Mittelbau desselben befindlichen innern Hof von ungefähr 25 000 Quadratfuss Oberfläche.\n Derselbe wird abgetreten bis zu einer in Verlängerung der Nordfassaden der Seitenflügel gezogenen Linie.\n Der in diesem Hofe befindliche Brunnen verbleibt der Einwohnergemeinde, welche denselben in gutem Zustande erhalten und ohne Genehmigung des Bundesrates an dem jetzigen baulichen Zustand mit Inbegriff der Statuen keine Veränderung vornehmen soll.\n Sie wird den Brunnen wie bis anhin mit Wasser versehen.\n Die Eidgenossenschaft verpflichtet sich, den Fortbestand des Brunnens auf ihrem Eigentum als Dienstbarkeit zu übernehmen.\n Der Brunnen sowie der Zugang zu demselben sollen dem Publikum zum angemessenen Hausgebrauch offenstehen.\nc. Eine Parzelle der sogenannten Vannazhalde von ungefähr 7280 Quadratfuss Oberfläche, auf welcher die Eidgenossenschaft ihr Gewächshaus erstellt hat. Ein Plan über die abgetretene Parzelle wird der Übereinkunft beigelegt.\n Die Schweizerische Eidgenossenschaft übernimmt jedoch die Verpflichtung, im Falle der Erbauung einer Strasse längs der Vannazhalde den in beiliegendem Plan gelb angelegten Abschnitt dieser Parzelle der Einwohnergemeinde zum Zwecke des Strassenbaues unentgeltlich wieder abzutreten.\n In diesem Falle ist der Bundesrat berechtigt, im Interesse der räumlichen Verhältnisse des Gewächshauses die Erstellung einer Stützmauer zu verlangen, deren Kosten alsdann zur einen Hälfte die Eidgenossenschaft und zur andern Hälfte die Einwohnergemeinde zu tragen hat.'},
 {'citation': 'Art. 2 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 2 112_0',
  'text': 'Die Einwohnergemeinde Bern wird ferner der Schweizerischen Eidgenossenschaft eine Summe von 500 000 Franken in zwischen dem Bundesrate und dem Einwohnergemeinderate zu vereinbarenden Terminen ausbezahlen. Die letzte Ratenzahlung wird jedenfalls spätestens auf Ende tausendachthundertsiebenundsiebenzig fällig.'},
 {'citation': 'Art. 3 Abs. 1 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 3 Abs. 1 112_0',
  'text': '1 Falls die Schweizerische Eidgenossenschaft zum Zwecke der Erstellung eines von ihr zu benutzenden neuen Verwaltungsgebäudes einen Teil des Bauplatzes zu erwerben wünscht, welcher zwischen der verlängerten Bundesgasse und der neuen Promenade der kleinen Schanze, im Eigentum der Einwohnergemeinde sich befindet, so erklärt sich letztere bereit, der Eidgenossenschaft den nötigen Bauplatz in der verlangten Ausdehnung zum Preise von 10 Franken per Quadratfuss zu übergeben, und zwar am östlichen Ende des oberwähnten Grundeigentums der Einwohnergemeinde, oder wenn die Bemühungen des Einwohnergemeinderates zur Beseitigung der Einspruchsrechte Dritter wider den Bau auf dieser Stelle erfolglos bleiben sollten, am westlichen Ende desselben. In beiden Fällen hat sich die Abtretung auf die ganze 120 Fuss messende Tiefe des Bauplatzes zu erstrecken. Die Einwohnergemeinde ist jedoch zu einer solchen Landabtretung nur verpflichtet, wenn der Bundesrat ein daheriges Begehren innerhalb drei Monaten nach Inkrafttreten dieser Übereinkunft an den Gemeinderat stellt.'},
 {'citation': 'Art. 3 Abs. 2 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 3 Abs. 2 112_0',
  'text': '2 Durch Anlage des neuen Verwaltungsgebäudes an hier bezeichneter Stelle übernimmt die Eidgenossenschaft bezüglich der Erstellung der Trottoirs und Trottoirsrinnen längs den Strassen, welche an das von ihr erworbene Grundeigentum grenzen, die gleichen Verpflichtungen, welche durch Artikel 5 der Übereinkunft vom 29. Januar 1872 zwischen Staat und Gemeinde Bern den Käufern von Bauparzellen auf dem Territorium des nördlichen Abschnittes der kleinen Schanze überbunden worden sind.'},
 {'citation': 'Art. 4 Abs. 1 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 4 Abs. 1 112_0',
  'text': '1 Die Einwohnergemeinde Bern übernimmt im fernern die Verpflichtung, auf der ihr gehörenden Vannazhalde keinerlei Gebäude zu errichten, deren Firste die jetzige Höhe der Bundesrathaus-Terrasse überragen würden.'},
 {'citation': 'Art. 4 Abs. 2 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 4 Abs. 2 112_0',
  'text': '2 Sie übernimmt auch die Verpflichtung, die erwähnte Terrasse zwischen dem Bundesrathause und der Vannazhalde als öffentliche Anlage zu erhalten.'},
 {'citation': 'Art. 4 Abs. 3 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 4 Abs. 3 112_0',
  'text': '3 Im Fall die Schweizerische Eidgenossenschaft von der ihr durch Artikel 3 eingeräumten Befugnis zur Beanspruchung von Land auf dem frühern Territorium der kleinen Schanze Gebrauch machen würde, so übernimmt überdies die Einwohnergemeinde auch dem Bunde gegenüber die Verpflichtung, die südlich von dem neu erstellten Verwaltungsgebäude verbleibenden Teile der kleinen Schanze als öffentliche Promenadenanlage zu erstellen und zu unterhalten.'},
 {'citation': 'Art. 5 Abs. 1 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 5 Abs. 1 112_0',
  'text': '1 Sollte infolge förmlichen Beschlusses der kompetenten Behörde das Bundesrathausgebäude auf hören, der Zentralverwaltung des Bundes zu dienen, so fallen die im Artikel 1 Buchstaben a, b, c bezeichneten Objekte in ihrem dannzumaligen Zustande als Eigentum an die Einwohnergemeinde Bern zurück und erlöschen die im ersten und zweiten Absatz des Artikels 4 seitens der Einwohnergemeinde übernommenen Verbindlichkeiten.'},
 {'citation': 'Art. 5 Abs. 2 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 5 Abs. 2 112_0',
  'text': '2 Für den nämlichen Fall übernimmt die Schweizerische Eidgenossenschaft die Verpflichtung, der Einwohnergemeinde Bern die im Artikel 2 vorgesehene Summe von 500 000 Franken zurückzuerstatten.'},
 {'citation': 'Art. 8 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 8 112_0',
  'text': 'Infolge Übernahme der durch diese Übereinkunft festgesetzten Leistungen der Einwohnergemeinde Bern erklärt die Schweizerische Eidgenossenschaft, dass dieselbe den ihr durch Bundesbeschlüsse vom 27. und 28. November 18484 auferlegten Verbindlichkeiten Genüge geleistet haben soll, und entbindet die Einwohnergemeinde Bern vollständig und abschliessend von jeder weitern Verpflichtung und Inanspruchnahme für Bundessitzleistungen.'},
 {'citation': 'Art. 9 Abs. 1 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 9 Abs. 1 112_0',
  'text': '1 Diese Übereinkunft tritt nach allseitiger endgültiger Ratifikation in Kraft.'},
 {'citation': 'Art. 9 Abs. 2 112',
  'title': 'Übereinkunft vom 22. Juni 1875 zwischen dem Schweizerischen Bundesrate und dem Einwohnergemeinderate der Stadt Bern betreffend die Leistungen der Stadt Bern an den Bundessitz',
  'chunk_id': 'Art. 9 Abs. 2 112_0',
  'text': '2 Der Schweizerische Bundesrat und der Einwohnergemeinderat der Stadt Bern sind mit der Vollziehung derselben beauftragt. Insbesondere sollen alle diejenigen Bestimmungen, welche dingliche Rechte zum Gegenstand haben, nach Mitgabe der Gesetze des Kantons Bern in rechtsverbindliche Form gebracht werden.'},
 {'citation': 'Art. 1 Abs. 1 116',
  'title': 'Verordnung vom 30. Mai 1994 über den Bundesfeiertag - Grundsatz',
  'chunk_id': 'Art. 1 Abs. 1 116_0',
  'text': '1 Der Bundesfeiertag ist ein den Sonntagen gleichgestellter arbeitsfreier Tag.'},
 {'citation': 'Art. 1 Abs. 2 116',
  'title': 'Verordnung vom 30. Mai 1994 über den Bundesfeiertag - Grundsatz',
  'chunk_id': 'Art. 1 Abs. 2 116_0',
  'text': '2 Er wird der Anzahl der Feiertage nach Artikel 18 Absatz 2 des Arbeitsgesetzes nicht angerechnet.'},
 {'citation': 'Art. 1 Abs. 3 116',
  'title': 'Verordnung vom 30. Mai 1994 über den Bundesfeiertag - Grundsatz',
  'chunk_id': 'Art. 1 Abs. 3 116_0',
  'text': '3 Für den arbeitsfreien Bundesfeiertag besteht volle Lohnzahlungspflicht durch den Arbeitgeber.'},
 {'citation': 'Art. 2 Abs. 1 116',
  'title': 'Verordnung vom 30. Mai 1994 über den Bundesfeiertag - Beschäftigung am Bundesfeiertag',
  'chunk_id': 'Art. 2 Abs. 1 116_0',
  'text': '1 Die Beschäftigung von Arbeitnehmerinnen und Arbeitnehmern am Bundesfeiertag richtet sich nach den einschlägigen Vorschriften über die Sonntagsarbeit.'},
 {'citation': 'Art. 2 Abs. 2 116',
  'title': 'Verordnung vom 30. Mai 1994 über den Bundesfeiertag - Beschäftigung am Bundesfeiertag',
  'chunk_id': 'Art. 2 Abs. 2 116_0',
  'text': '2 Wo keine gesetzlichen Vorschriften anwendbar sind, können Arbeitnehmerinnen und Arbeitnehmer am Bundesfeiertag beschäftigt werden, wenn es aus betrieblichen Gründen notwendig ist. Arbeit bis zu fünf Stunden Dauer ist durch Freizeit von gleicher Dauer, Arbeit von mehr als fünf Stunden durch einen Ersatzruhetag auszugleichen.'},
 {'citation': 'Art. 3 116',
  'title': 'Verordnung vom 30. Mai 1994 über den Bundesfeiertag - Vorbehalt kantonalen Rechts',
  'chunk_id': 'Art. 3 116_0',
  'text': 'Vorbehalten bleiben die kantonalen Bestimmungen über die Sonntagsruhe und die Öffnungszeiten von Betrieben, die dem Detailverkauf, der Bewirtung oder der Unterhaltung dienen.'},
 {'citation': 'Art. 4 116',
  'title': 'Verordnung vom 30. Mai 1994 über den Bundesfeiertag - Änderung bisherigen Rechts',
  'chunk_id': 'Art. 4 116_0',
  'text': '...'},
 {'citation': 'Art. 1 Abs. 1 122.1',
  'title': 'Bundesgesetz vom 20. Dezember 2024 über das Verbot der Hamas sowie verwandter Organisationen',
  'chunk_id': 'Art. 1 Abs. 1 122.1_0',
  'text': '1 Folgende Organisationen und Gruppierungen sind verboten:a. die Hamas;\nb. Tarn- und Nachfolgeorganisationen der Hamas sowie Organisationen und Gruppierungen, die im Auftrag oder im Namen der Hamas handeln.'},
 {'citation': 'Art. 1 Abs. 2 122.1',
  'title': 'Bundesgesetz vom 20. Dezember 2024 über das Verbot der Hamas sowie verwandter Organisationen',
  'chunk_id': 'Art. 1 Abs. 2 122.1_0',
  'text': '2 Der Bundesrat kann Organisationen und Gruppierungen verbieten, deren Führungspersonen, Zielsetzung oder Mittel mit denjenigen der Hamas übereinstimmen und die mittelbar oder unmittelbar terroristische oder gewalttätig-extremistische Aktivitäten unterstützen und damit die innere oder äussere Sicherheit konkret bedrohen. Er konsultiert vorgängig die für die Sicherheitspolitik zuständigen Kommissionen. Das Verbot ist zu befristen; es kann verlängert werden.'},
 {'citation': 'Art. 1 Abs. 3 122.1',
  'title': 'Bundesgesetz vom 20. Dezember 2024 über das Verbot der Hamas sowie verwandter Organisationen',
  'chunk_id': 'Art. 1 Abs. 3 122.1_0',
  'text': '3 Die verbotenen Organisationen und Gruppierungen gelten als terroristische Organisationen nach Artikel 260ter Absatz 1 Buchstabe a Ziffer 2 des Strafgesetzbuchs3.'},
 {'citation': 'Art. 2 122.1',
  'title': 'Bundesgesetz vom 20. Dezember 2024 über das Verbot der Hamas sowie verwandter Organisationen',
  'chunk_id': 'Art. 2 122.1_0',
  'text': 'Die Verfolgung und Beurteilung der Beteiligung an einer verbotenen Organisation oder Gruppierung und der Unterstützung einer solchen Organisation oder Gruppierung unterstehen der Bundesgerichtsbarkeit.'},
 {'citation': 'Art. 3 122.1',
  'title': 'Bundesgesetz vom 20. Dezember 2024 über das Verbot der Hamas sowie verwandter Organisationen',
  'chunk_id': 'Art. 3 122.1_0',
  'text': '…4'},
 {'citation': 'Art. 4 Abs. 1 122.1',
  'title': 'Bundesgesetz vom 20. Dezember 2024 über das Verbot der Hamas sowie verwandter Organisationen',
  'chunk_id': 'Art. 4 Abs. 1 122.1_0',
  'text': '1 Dieses Gesetz untersteht dem fakultativen Referendum.'},
 {'citation': 'Art. 4 Abs. 2 122.1',
  'title': 'Bundesgesetz vom 20. Dezember 2024 über das Verbot der Hamas sowie verwandter Organisationen',
  'chunk_id': 'Art. 4 Abs. 2 122.1_0',
  'text': '2 Der Bundesrat bestimmt das Inkrafttreten.'},
 {'citation': 'Art. 4 Abs. 3 122.1',
  'title': 'Bundesgesetz vom 20. Dezember 2024 über das Verbot der Hamas sowie verwandter Organisationen',
  'chunk_id': 'Art. 4 Abs. 3 122.1_0',
  'text': '3 Dieses Gesetz tritt fünf Jahre nach Inkrafttreten ausser Kraft.'},
 {'citation': 'Art. 1 Abs. 1 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Kanton Zürich',
  'chunk_id': 'Art. 1 Abs. 1 131.211_0',
  'text': '1 Der Kanton Zürich ist ein souveräner Stand der Schweizerischen Eidgenossenschaft.'},
 {'citation': 'Art. 1 Abs. 2 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Kanton Zürich',
  'chunk_id': 'Art. 1 Abs. 2 131.211_0',
  'text': '2 Er gründet auf der Eigen- und Mitverantwortung seiner Einwohnerinnen und Einwohner.'},
 {'citation': 'Art. 1 Abs. 3 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Kanton Zürich',
  'chunk_id': 'Art. 1 Abs. 3 131.211_0',
  'text': '3 Die Staatsgewalt beruht auf dem Volk. Sie wird von den Stimmberechtigten und den Behörden ausgeübt.'},
 {'citation': 'Art. 1 Abs. 4 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Kanton Zürich',
  'chunk_id': 'Art. 1 Abs. 4 131.211_0',
  'text': '4 Der Kanton anerkennt die Selbstständigkeit der Gemeinden.'},
 {'citation': 'Art. 2 Abs. 1 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Rechtsstaatliche Grundsätze',
  'chunk_id': 'Art. 2 Abs. 1 131.211_0',
  'text': '1 Grundlage und Schranke staatlichen Handelns ist das Recht.'},
 {'citation': 'Art. 2 Abs. 2 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Rechtsstaatliche Grundsätze',
  'chunk_id': 'Art. 2 Abs. 2 131.211_0',
  'text': '2 Staatliches Handeln muss im öffentlichen Interesse liegen und verhältnismässig sein.'},
 {'citation': 'Art. 2 Abs. 3 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Rechtsstaatliche Grundsätze',
  'chunk_id': 'Art. 2 Abs. 3 131.211_0',
  'text': '3 Behörden und Private handeln nach Treu und Glauben.'},
 {'citation': 'Art. 3 Abs. 1 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Gewaltenteilung',
  'chunk_id': 'Art. 3 Abs. 1 131.211_0',
  'text': '1 Der Aufbau des Staates und die Ausübung staatlicher Macht beruhen auf dem Grundsatz der Gewaltenteilung.'},
 {'citation': 'Art. 3 Abs. 2 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Gewaltenteilung',
  'chunk_id': 'Art. 3 Abs. 2 131.211_0',
  'text': '2 Niemand darf staatliche Macht unkontrolliert oder unbegrenzt ausüben.'},
 {'citation': 'Art. 4 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Zusammenarbeit',
  'chunk_id': 'Art. 4 131.211_0',
  'text': 'Der Kanton arbeitet mit den Gemeinden, den anderen Kantonen, dem Bund und, in seinem Zuständigkeitsbereich, mit dem Ausland zusammen.'},
 {'citation': 'Art. 5 Abs. 1 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Subsidiarität',
  'chunk_id': 'Art. 5 Abs. 1 131.211_0',
  'text': '1 Jede Person nimmt Verantwortung für sich selber wahr und trägt nach ihren Kräften zur Bewältigung der Aufgaben in Staat und Gesellschaft bei.'},
 {'citation': 'Art. 5 Abs. 2 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Subsidiarität',
  'chunk_id': 'Art. 5 Abs. 2 131.211_0',
  'text': '2 Der Kanton und die Gemeinden anerkennen die Initiative von Einzelnen und von Organisationen zur Förderung des Gemeinwohls. Sie fördern die Hilfe zur Selbsthilfe.'},
 {'citation': 'Art. 5 Abs. 3 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Subsidiarität',
  'chunk_id': 'Art. 5 Abs. 3 131.211_0',
  'text': '3 Sie nehmen Aufgaben von öffentlichem Interesse wahr, soweit Private sie nicht angemessen erfüllen.'},
 {'citation': 'Art. 6 Abs. 1 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Nachhaltigkeit',
  'chunk_id': 'Art. 6 Abs. 1 131.211_0',
  'text': '1 Kanton und Gemeinden sorgen für die Erhaltung der Lebensgrundlagen.'},
 {'citation': 'Art. 6 Abs. 2 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Nachhaltigkeit',
  'chunk_id': 'Art. 6 Abs. 2 131.211_0',
  'text': '2 In Verantwortung für die kommenden Generationen sind sie einer ökologisch, wirtschaftlich und sozial nachhaltigen Entwicklung verpflichtet.'},
 {'citation': 'Art. 7 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Dialog',
  'chunk_id': 'Art. 7 131.211_0',
  'text': 'Kanton und Gemeinden schaffen günstige Voraussetzungen für den Dialog zwischen den Kulturen, Weltanschauungen und Religionen.'},
 {'citation': 'Art. 8 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Innovation',
  'chunk_id': 'Art. 8 131.211_0',
  'text': 'Kanton und Gemeinden schaffen günstige Rahmenbedingungen für wirtschaftliche, kulturelle, soziale und ökologische Innovation.'},
 {'citation': 'Art. 9 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Schutz der Menschenwürde',
  'chunk_id': 'Art. 9 131.211_0',
  'text': 'Die Würde des Menschen ist unantastbar.'},
 {'citation': 'Art. 10 Abs. 1 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Gewährleistung der Grundrechte',
  'chunk_id': 'Art. 10 Abs. 1 131.211_0',
  'text': '1 Die Menschenrechte und Grundrechte sind gemäss der Bundesverfassung2, den für die Schweiz verbindlichen internationalen Abkommen und der Kantonsverfassung gewährleistet.'},
 {'citation': 'Art. 10 Abs. 2 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Gewährleistung der Grundrechte',
  'chunk_id': 'Art. 10 Abs. 2 131.211_0',
  'text': '2 Die Bestimmungen der Bundesverfassung über die Verwirklichung und die Einschränkung der Grundrechte gelten auch für die Grundrechte des kantonalen Rechts.'},
 {'citation': 'Art. 11 Abs. 1 131.211',
  'title': 'Verfassung des Kantons Zürich, vom 27. Februar 2005 - Rechtsgleichheit',

In [7]:
for i, j in law[0:5].iterrows() :
    print(f"i = {i}")
    #print(f"j = {j}")
    print(j)
    print(f"type = {type(j)}")

i = 0
citation                                           Art. 1 112
text        Die Einwohnergemeinde Bern tritt der Schweizer...
title       Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
Name: 0, dtype: object
type = <class 'pandas.core.series.Series'>
i = 1
citation                                           Art. 2 112
text        Die Einwohnergemeinde Bern wird ferner der Sch...
title       Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
Name: 1, dtype: object
type = <class 'pandas.core.series.Series'>
i = 2
citation                                    Art. 3 Abs. 1 112
text        1 Falls die Schweizerische Eidgenossenschaft z...
title       Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
Name: 2, dtype: object
type = <class 'pandas.core.series.Series'>
i = 3
citation                                    Art. 3 Abs. 2 112
text        2 Durch Anlage des neuen Verwaltungsgebäudes a...
title       Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
Name: 3, dtype: object
type = <class 'pandas.core.series.Series'>
i = 4
citation                                    Art. 4 Abs. 1 112
text        1 Die Einwohnergemeinde Bern übernimmt im fern...
title       Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
Name: 4, dtype: object
type = <class 'pandas.core.series.Series'>

In [25]:
sample = law.iloc[0]["text"]
chunks = hybrid_chunk(sample)

for c in chunks[0:20]:
    print(c)
    print("----")

Die Einwohnergemeinde Bern tritt der Schweizerischen Eidgenossenschaft unentgeltlich als Eigentum ab:a. Das Gebäude des Bundesrathauses im roten Quartier der Stadt Bern, mit Nr. 229 bezeichnet, nebst den in demselben enthaltenen Einrichtungen und Mobilien, welche der Einwohnergemeinde angehören, und unter Vorbehalt der im Artikel 62 von der Einwohnergemeinde reservierten Einrichtungen und Gegenstände;
b. den zwischen den Seitenflügeln des Bundesrathauses und nördlich von dem Mittelbau desselben befindlichen innern Hof von ungefähr 25 000 Quadratfuss Oberfläche.
 Derselbe wird abgetreten bis zu einer in Verlängerung der Nordfassaden der Seitenflügel gezogenen Linie.
 Der in diesem Hofe befindliche Brunnen verbleibt der Einwohnergemeinde, welche denselben in gutem Zustande erhalten und ohne Genehmigung des Bundesrates an dem jetzigen baulichen Zustand mit Inbegriff der Statuen keine Veränderung vornehmen soll.
 Sie wird den Brunnen wie bis anhin mit Wasser versehen.
 Die Eidgenossenschaft verpflichtet sich, den Fortbestand des Brunnens auf ihrem Eigentum als Dienstbarkeit zu übernehmen.
 Der Brunnen sowie der Zugang zu demselben sollen dem Publikum zum angemessenen Hausgebrauch offenstehen.
c. Eine Parzelle der sogenannten Vannazhalde von ungefähr 7280 Quadratfuss Oberfläche, auf welcher die Eidgenossenschaft ihr Gewächshaus erstellt hat. Ein Plan über die abgetretene Parzelle wird der Übereinkunft beigelegt.
 Die Schweizerische Eidgenossenschaft übernimmt jedoch die Verpflichtung, im Falle der Erbauung einer Strasse längs der Vannazhalde den in beiliegendem Plan gelb angelegten Abschnitt dieser Parzelle der Einwohnergemeinde zum Zwecke des Strassenbaues unentgeltlich wieder abzutreten.
 In diesem Falle ist der Bundesrat berechtigt, im Interesse der räumlichen Verhältnisse des Gewächshauses die Erstellung einer Stützmauer zu verlangen, deren Kosten alsdann zur einen Hälfte die Eidgenossenschaft und zur andern Hälfte die Einwohnergemeinde zu tragen hat.
----

In [12]:
law["text"][3]

'2 Durch Anlage des neuen Verwaltungsgebäudes an hier bezeichneter Stelle übernimmt die Eidgenossenschaft bezüglich der Erstellung der Trottoirs und Trottoirsrinnen längs den Strassen, welche an das von ihr erworbene Grundeigentum grenzen, die gleichen Verpflichtungen, welche durch Artikel 5 der Übereinkunft vom 29. Januar 1872 zwischen Staat und Gemeinde Bern den Käufern von Bauparzellen auf dem Territorium des nördlichen Abschnittes der kleinen Schanze überbunden worden sind.'

In [17]:
import re

In [ ]:
def split_by_articles(text: str) -> list[dict[str, str]]:
    """
    Split legal text by articles. Handles formats like:
    - Art. 1, Art. 1a, Art. 1 Abs. 1, Abs. 2, § 1, etc.
    Returns list of dicts with article info and content
    """
    # Enhanced pattern for German/Swiss legal format
    article_pattern = r"((?:Art\.?|§)\s*\d+[a-zA-Z]*(?:\s+Abs\.?\s*\d+)?)"
    parts = re.split(article_pattern, text)

    chunks = []
    for i in range(1, len(parts), 2):
        article_header = parts[i].strip()
        content = parts[i+1].strip() if i+1 < len(parts) else ""
        
        if content:  # Only include if there's content
            chunks.append({
                "article": article_header,
                "content": content,
                "full_text": article_header + " " + content
            })
    print(chunks)
    return chunks if chunks else [{"article": "Full Text", "content": text, "full_text": text}]

In [19]:
for _, row in law.iterrows() :
    text = row["text"]
    split_by_articles(text)

In [24]:
# Get chunks from a sample law text
sample_text = law.iloc[0]["text"]
chunks = split_by_articles(sample_text)

# Display the chunks
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:")
    print(chunk)
    print("----")

Chunk 0:
{'article': 'Full Text', 'content': 'Die Einwohnergemeinde Bern tritt der Schweizerischen Eidgenossenschaft unentgeltlich als Eigentum ab:a. Das Gebäude des Bundesrathauses im roten Quartier der Stadt Bern, mit Nr. 229 bezeichnet, nebst den in demselben enthaltenen Einrichtungen und Mobilien, welche der Einwohnergemeinde angehören, und unter Vorbehalt der im Artikel 62 von der Einwohnergemeinde reservierten Einrichtungen und Gegenstände;\nb. den zwischen den Seitenflügeln des Bundesrathauses und nördlich von dem Mittelbau desselben befindlichen innern Hof von ungefähr 25 000 Quadratfuss Oberfläche.\n Derselbe wird abgetreten bis zu einer in Verlängerung der Nordfassaden der Seitenflügel gezogenen Linie.\n Der in diesem Hofe befindliche Brunnen verbleibt der Einwohnergemeinde, welche denselben in gutem Zustande erhalten und ohne Genehmigung des Bundesrates an dem jetzigen baulichen Zustand mit Inbegriff der Statuen keine Veränderung vornehmen soll.\n Sie wird den Brunnen wie bis anhin mit Wasser versehen.\n Die Eidgenossenschaft verpflichtet sich, den Fortbestand des Brunnens auf ihrem Eigentum als Dienstbarkeit zu übernehmen.\n Der Brunnen sowie der Zugang zu demselben sollen dem Publikum zum angemessenen Hausgebrauch offenstehen.\nc. Eine Parzelle der sogenannten Vannazhalde von ungefähr 7280 Quadratfuss Oberfläche, auf welcher die Eidgenossenschaft ihr Gewächshaus erstellt hat. Ein Plan über die abgetretene Parzelle wird der Übereinkunft beigelegt.\n Die Schweizerische Eidgenossenschaft übernimmt jedoch die Verpflichtung, im Falle der Erbauung einer Strasse längs der Vannazhalde den in beiliegendem Plan gelb angelegten Abschnitt dieser Parzelle der Einwohnergemeinde zum Zwecke des Strassenbaues unentgeltlich wieder abzutreten.\n In diesem Falle ist der Bundesrat berechtigt, im Interesse der räumlichen Verhältnisse des Gewächshauses die Erstellung einer Stützmauer zu verlangen, deren Kosten alsdann zur einen Hälfte die Eidgenossenschaft und zur andern Hälfte die Einwohnergemeinde zu tragen hat.', 'full_text': 'Die Einwohnergemeinde Bern tritt der Schweizerischen Eidgenossenschaft unentgeltlich als Eigentum ab:a. Das Gebäude des Bundesrathauses im roten Quartier der Stadt Bern, mit Nr. 229 bezeichnet, nebst den in demselben enthaltenen Einrichtungen und Mobilien, welche der Einwohnergemeinde angehören, und unter Vorbehalt der im Artikel 62 von der Einwohnergemeinde reservierten Einrichtungen und Gegenstände;\nb. den zwischen den Seitenflügeln des Bundesrathauses und nördlich von dem Mittelbau desselben befindlichen innern Hof von ungefähr 25 000 Quadratfuss Oberfläche.\n Derselbe wird abgetreten bis zu einer in Verlängerung der Nordfassaden der Seitenflügel gezogenen Linie.\n Der in diesem Hofe befindliche Brunnen verbleibt der Einwohnergemeinde, welche denselben in gutem Zustande erhalten und ohne Genehmigung des Bundesrates an dem jetzigen baulichen Zustand mit Inbegriff der Statuen keine Veränderung vornehmen soll.\n Sie wird den Brunnen wie bis anhin mit Wasser versehen.\n Die Eidgenossenschaft verpflichtet sich, den Fortbestand des Brunnens auf ihrem Eigentum als Dienstbarkeit zu übernehmen.\n Der Brunnen sowie der Zugang zu demselben sollen dem Publikum zum angemessenen Hausgebrauch offenstehen.\nc. Eine Parzelle der sogenannten Vannazhalde von ungefähr 7280 Quadratfuss Oberfläche, auf welcher die Eidgenossenschaft ihr Gewächshaus erstellt hat. Ein Plan über die abgetretene Parzelle wird der Übereinkunft beigelegt.\n Die Schweizerische Eidgenossenschaft übernimmt jedoch die Verpflichtung, im Falle der Erbauung einer Strasse längs der Vannazhalde den in beiliegendem Plan gelb angelegten Abschnitt dieser Parzelle der Einwohnergemeinde zum Zwecke des Strassenbaues unentgeltlich wieder abzutreten.\n In diesem Falle ist der Bundesrat berechtigt, im Interesse der räumlichen Verhältnisse des Gewächshauses die Erstellung einer Stützmauer zu verlangen, deren Kosten alsdann zur einen Hälfte die Eidgenossenschaft und zur andern Hälfte die Einwohnergemeinde zu tragen hat.'}
----

In [5]:
test_query = val['query'].iloc[0]

In [6]:
test_query

'May a court lawfully order a three‑month extension of pre‑trial detention under Art. 221 Abs. 1 lit. b StPO (risk of collusion) consistent with the principle of proportionality when the accused—detained after an alleged late‑night assault and theft of a courier satchel containing, inter alia, €5,600—was remanded by an order dated 18 October 2024 for a maximum period up to 15 January 2025, the prosecutor sought an extension on 10 December 2024 primarily citing a concrete risk that the detainee would influence witnesses or tamper with evidence and a risk of reoffending, while the detainee opposed the extension on the ground that most witnesses have already been interviewed, the investigative steps still pending are essentially technical (phone data extraction, CCTV image analysis, and bank record checks), his release would therefore not jeopardize the inquiry, and the alleged victim has withdrawn the complaint—i.e. does the asserted concrete risk of collusion and considerations of proportionality justify a three‑month prolongation in these circumstances?'

In [10]:
val["query"][0]

'May a court lawfully order a three‑month extension of pre‑trial detention under Art. 221 Abs. 1 lit. b StPO (risk of collusion) consistent with the principle of proportionality when the accused—detained after an alleged late‑night assault and theft of a courier satchel containing, inter alia, €5,600—was remanded by an order dated 18 October 2024 for a maximum period up to 15 January 2025, the prosecutor sought an extension on 10 December 2024 primarily citing a concrete risk that the detainee would influence witnesses or tamper with evidence and a risk of reoffending, while the detainee opposed the extension on the ground that most witnesses have already been interviewed, the investigative steps still pending are essentially technical (phone data extraction, CCTV image analysis, and bank record checks), his release would therefore not jeopardize the inquiry, and the alleged victim has withdrawn the complaint—i.e. does the asserted concrete risk of collusion and considerations of proportionality justify a three‑month prolongation in these circumstances?'

In [14]:
law["text"][5:8]

5    2 Sie übernimmt auch die Verpflichtung, die er...
6    3 Im Fall die Schweizerische Eidgenossenschaft...
7    1 Sollte infolge förmlichen Beschlusses der ko...
Name: text, dtype: object

In [15]:
law["text"][6]

'3 Im Fall die Schweizerische Eidgenossenschaft von der ihr durch Artikel 3 eingeräumten Befugnis zur Beanspruchung von Land auf dem frühern Territorium der kleinen Schanze Gebrauch machen würde, so übernimmt überdies die Einwohnergemeinde auch dem Bunde gegenüber die Verpflichtung, die südlich von dem neu erstellten Verwaltungsgebäude verbleibenden Teile der kleinen Schanze als öffentliche Promenadenanlage zu erstellen und zu unterhalten.'

In [17]:
[str(doc).lower().split() for doc in law['text'][5:8].fillna("")]

[['2',
  'sie',
  'übernimmt',
  'auch',
  'die',
  'verpflichtung,',
  'die',
  'erwähnte',
  'terrasse',
  'zwischen',
  'dem',
  'bundesrathause',
  'und',
  'der',
  'vannazhalde',
  'als',
  'öffentliche',
  'anlage',
  'zu',
  'erhalten.'],
 ['3',
  'im',
  'fall',
  'die',
  'schweizerische',
  'eidgenossenschaft',
  'von',
  'der',
  'ihr',
  'durch',
  'artikel',
  '3',
  'eingeräumten',
  'befugnis',
  'zur',
  'beanspruchung',
  'von',
  'land',
  'auf',
  'dem',
  'frühern',
  'territorium',
  'der',
  'kleinen',
  'schanze',
  'gebrauch',
  'machen',
  'würde,',
  'so',
  'übernimmt',
  'überdies',
  'die',
  'einwohnergemeinde',
  'auch',
  'dem',
  'bunde',
  'gegenüber',
  'die',
  'verpflichtung,',
  'die',
  'südlich',
  'von',
  'dem',
  'neu',
  'erstellten',
  'verwaltungsgebäude',
  'verbleibenden',
  'teile',
  'der',
  'kleinen',
  'schanze',
  'als',
  'öffentliche',
  'promenadenanlage',
  'zu',
  'erstellen',
  'und',
  'zu',
  'unterhalten.'],
 ['1',
  'sollte',
  'infolge',
  'förmlichen',
  'beschlusses',
  'der',
  'kompetenten',
  'behörde',
  'das',
  'bundesrathausgebäude',
  'auf',
  'hören,',
  'der',
  'zentralverwaltung',
  'des',
  'bundes',
  'zu',
  'dienen,',
  'so',
  'fallen',
  'die',
  'im',
  'artikel',
  '1',
  'buchstaben',
  'a,',
  'b,',
  'c',
  'bezeichneten',
  'objekte',
  'in',
  'ihrem',
  'dannzumaligen',
  'zustande',
  'als',
  'eigentum',
  'an',
  'die',
  'einwohnergemeinde',
  'bern',
  'zurück',
  'und',
  'erlöschen',
  'die',
  'im',
  'ersten',
  'und',
  'zweiten',
  'absatz',
  'des',
  'artikels',
  '4',
  'seitens',
  'der',
  'einwohnergemeinde',
  'übernommenen',
  'verbindlichkeiten.']]

In [17]:
from rank_bm25 import BM25Okapi
import time

print("Preparing BM25 on the FULL laws corpus...")
start_time = time.time()

# Simple tokenization: lowercasing and splitting by space 
# We fill NaN values with empty string to avoid errors
tokenized_corpus = [str(doc).lower().split() for doc in law['text'].fillna("")]

# Initialize BM25 model
bm25 = BM25Okapi(tokenized_corpus)

print(f"BM25 indexing finished in {time.time() - start_time:.2f} seconds.")

# Prepare the same test query 
test_query = val['query'].iloc[0]
tokenized_query = test_query.lower().split()

print("\nSearching with BM25...")
# Get top 3 scores and their indices 
bm25_scores = bm25.get_scores(tokenized_query)
top_k = 3

Preparing BM25 on the FULL laws corpus...
BM25 indexing finished in 3.76 seconds.

Searching with BM25...

In [18]:
bm25_scores

array([2.60583334, 0.96223219, 5.3279724 , ..., 0.59116989, 0.        ,
       1.48323831], shape=(175933,))

In [19]:
np.argsort(bm25_scores)

array([175894,  87281, 175843, ...,  62462,  50367,   7249],
      shape=(175933,))

In [20]:
np.argsort(bm25_scores)[-3:]# [::-1]

array([62462, 50367,  7249])

In [30]:
val[val['gold_citations'] == "Art. 3 Abs. 1 221.434"]

Empty DataFrame
Columns: [query_id, query, gold_citations]
Index: []

In [29]:
law["citation"][7249]

'Art. 3 Abs. 1 221.434'

In [21]:
top_indices = np.argsort(bm25_scores)[-top_k:][::-1]

In [11]:
top_indices

array([21, 22,  3])

In [15]:
tokenized_corpus = [str(doc).lower().split() for doc in law['text'][0:50].fillna("")]

In [16]:
tokenized_corpus

[['die',
  'einwohnergemeinde',
  'bern',
  'tritt',
  'der',
  'schweizerischen',
  'eidgenossenschaft',
  'unentgeltlich',
  'als',
  'eigentum',
  'ab:a.',
  'das',
  'gebäude',
  'des',
  'bundesrathauses',
  'im',
  'roten',
  'quartier',
  'der',
  'stadt',
  'bern,',
  'mit',
  'nr.',
  '229',
  'bezeichnet,',
  'nebst',
  'den',
  'in',
  'demselben',
  'enthaltenen',
  'einrichtungen',
  'und',
  'mobilien,',
  'welche',
  'der',
  'einwohnergemeinde',
  'angehören,',
  'und',
  'unter',
  'vorbehalt',
  'der',
  'im',
  'artikel',
  '62',
  'von',
  'der',
  'einwohnergemeinde',
  'reservierten',
  'einrichtungen',
  'und',
  'gegenstände;',
  'b.',
  'den',
  'zwischen',
  'den',
  'seitenflügeln',
  'des',
  'bundesrathauses',
  'und',
  'nördlich',
  'von',
  'dem',
  'mittelbau',
  'desselben',
  'befindlichen',
  'innern',
  'hof',
  'von',
  'ungefähr',
  '25',
  '000',
  'quadratfuss',
  'oberfläche.',
  'derselbe',
  'wird',
  'abgetreten',
  'bis',
  'zu',
  'einer',
  'in',
  'verlängerung',
  'der',
  'nordfassaden',
  'der',
  'seitenflügel',
  'gezogenen',
  'linie.',
  'der',
  'in',
  'diesem',
  'hofe',
  'befindliche',
  'brunnen',
  'verbleibt',
  'der',
  'einwohnergemeinde,',
  'welche',
  'denselben',
  'in',
  'gutem',
  'zustande',
  'erhalten',
  'und',
  'ohne',
  'genehmigung',
  'des',
  'bundesrates',
  'an',
  'dem',
  'jetzigen',
  'baulichen',
  'zustand',
  'mit',
  'inbegriff',
  'der',
  'statuen',
  'keine',
  'veränderung',
  'vornehmen',
  'soll.',
  'sie',
  'wird',
  'den',
  'brunnen',
  'wie',
  'bis',
  'anhin',
  'mit',
  'wasser',
  'versehen.',
  'die',
  'eidgenossenschaft',
  'verpflichtet',
  'sich,',
  'den',
  'fortbestand',
  'des',
  'brunnens',
  'auf',
  'ihrem',
  'eigentum',
  'als',
  'dienstbarkeit',
  'zu',
  'übernehmen.',
  'der',
  'brunnen',
  'sowie',
  'der',
  'zugang',
  'zu',
  'demselben',
  'sollen',
  'dem',
  'publikum',
  'zum',
  'angemessenen',
  'hausgebrauch',
  'offenstehen.',
  'c.',
  'eine',
  'parzelle',
  'der',
  'sogenannten',
  'vannazhalde',
  'von',
  'ungefähr',
  '7280',
  'quadratfuss',
  'oberfläche,',
  'auf',
  'welcher',
  'die',
  'eidgenossenschaft',
  'ihr',
  'gewächshaus',
  'erstellt',
  'hat.',
  'ein',
  'plan',
  'über',
  'die',
  'abgetretene',
  'parzelle',
  'wird',
  'der',
  'übereinkunft',
  'beigelegt.',
  'die',
  'schweizerische',
  'eidgenossenschaft',
  'übernimmt',
  'jedoch',
  'die',
  'verpflichtung,',
  'im',
  'falle',
  'der',
  'erbauung',
  'einer',
  'strasse',
  'längs',
  'der',
  'vannazhalde',
  'den',
  'in',
  'beiliegendem',
  'plan',
  'gelb',
  'angelegten',
  'abschnitt',
  'dieser',
  'parzelle',
  'der',
  'einwohnergemeinde',
  'zum',
  'zwecke',
  'des',
  'strassenbaues',
  'unentgeltlich',
  'wieder',
  'abzutreten.',
  'in',
  'diesem',
  'falle',
  'ist',
  'der',
  'bundesrat',
  'berechtigt,',
  'im',
  'interesse',
  'der',
  'räumlichen',
  'verhältnisse',
  'des',
  'gewächshauses',
  'die',
  'erstellung',
  'einer',
  'stützmauer',
  'zu',
  'verlangen,',
  'deren',
  'kosten',
  'alsdann',
  'zur',
  'einen',
  'hälfte',
  'die',
  'eidgenossenschaft',
  'und',
  'zur',
  'andern',
  'hälfte',
  'die',
  'einwohnergemeinde',
  'zu',
  'tragen',
  'hat.'],
 ['die',
  'einwohnergemeinde',
  'bern',
  'wird',
  'ferner',
  'der',
  'schweizerischen',
  'eidgenossenschaft',
  'eine',
  'summe',
  'von',
  '500',
  '000',
  'franken',
  'in',
  'zwischen',
  'dem',
  'bundesrate',
  'und',
  'dem',
  'einwohnergemeinderate',
  'zu',
  'vereinbarenden',
  'terminen',
  'ausbezahlen.',
  'die',
  'letzte',
  'ratenzahlung',
  'wird',
  'jedenfalls',
  'spätestens',
  'auf',
  'ende',
  'tausendachthundertsiebenundsiebenzig',
  'fällig.'],
 ['1',
  'falls',
  'die',
  'schweizerische',
  'eidgenossenschaft',
  'zum',
  'zwecke',
  'der',
  'erstellung',
  'eines',
  'von',
  'ihr',
  'zu',
  'benutzenden',
  'neuen',
  'verwaltungsgebäudes',
  'einen',
  'teil',
  'des',
  'bauplatzes',
  'zu',
  'erwerben',
  'wünscht,',
  'welcher',
  'zwischen',
  'der',
  'verlängerten',
  'bundesgasse',
  'und',
  'der',
  'neuen',
  'promenade',
  'der',
  'kleinen',
  'schanze,',
  'im',
  'eigentum',
  'der',
  'einwohnergemeinde',
  'sich',
  'befindet,',
  'so',
  'erklärt',
  'sich',
  'letztere',
  'bereit,',
  'der',
  'eidgenossenschaft',
  'den',
  'nötigen',
  'bauplatz',
  'in',
  'der',
  'verlangten',
  'ausdehnung',
  'zum',
  'preise',
  'von',
  '10',
  'franken',
  'per',
  'quadratfuss',
  'zu',
  'übergeben,',
  'und',
  'zwar',
  'am',
  'östlichen',
  'ende',
  'des',
  'oberwähnten',
  'grundeigentums',
  'der',
  'einwohnergemeinde,',
  'oder',
  'wenn',
  'die',
  'bemühungen',
  'des',
  'einwohnergemeinderates',
  'zur',
  'beseitigung',
  'der',
  'einspruchsrechte',
  'dritter',
  'wider',
  'den',
  'bau',
  'auf',
  'dieser',
  'stelle',
  'erfolglos',
  'bleiben',
  'sollten,',
  'am',
  'westlichen',
  'ende',
  'desselben.',
  'in',
  'beiden',
  'fällen',
  'hat',
  'sich',
  'die',
  'abtretung',
  'auf',
  'die',
  'ganze',
  '120',
  'fuss',
  'messende',
  'tiefe',
  'des',
  'bauplatzes',
  'zu',
  'erstrecken.',
  'die',
  'einwohnergemeinde',
  'ist',
  'jedoch',
  'zu',
  'einer',
  'solchen',
  'landabtretung',
  'nur',
  'verpflichtet,',
  'wenn',
  'der',
  'bundesrat',
  'ein',
  'daheriges',
  'begehren',
  'innerhalb',
  'drei',
  'monaten',
  'nach',
  'inkrafttreten',
  'dieser',
  'übereinkunft',
  'an',
  'den',
  'gemeinderat',
  'stellt.'],
 ['2',
  'durch',
  'anlage',
  'des',
  'neuen',
  'verwaltungsgebäudes',
  'an',
  'hier',
  'bezeichneter',
  'stelle',
  'übernimmt',
  'die',
  'eidgenossenschaft',
  'bezüglich',
  'der',
  'erstellung',
  'der',
  'trottoirs',
  'und',
  'trottoirsrinnen',
  'längs',
  'den',
  'strassen,',
  'welche',
  'an',
  'das',
  'von',
  'ihr',
  'erworbene',
  'grundeigentum',
  'grenzen,',
  'die',
  'gleichen',
  'verpflichtungen,',
  'welche',
  'durch',
  'artikel',
  '5',
  'der',
  'übereinkunft',
  'vom',
  '29.',
  'januar',
  '1872',
  'zwischen',
  'staat',
  'und',
  'gemeinde',
  'bern',
  'den',
  'käufern',
  'von',
  'bauparzellen',
  'auf',
  'dem',
  'territorium',
  'des',
  'nördlichen',
  'abschnittes',
  'der',
  'kleinen',
  'schanze',
  'überbunden',
  'worden',
  'sind.'],
 ['1',
  'die',
  'einwohnergemeinde',
  'bern',
  'übernimmt',
  'im',
  'fernern',
  'die',
  'verpflichtung,',
  'auf',
  'der',
  'ihr',
  'gehörenden',
  'vannazhalde',
  'keinerlei',
  'gebäude',
  'zu',
  'errichten,',
  'deren',
  'firste',
  'die',
  'jetzige',
  'höhe',
  'der',
  'bundesrathaus-terrasse',
  'überragen',
  'würden.'],
 ['2',
  'sie',
  'übernimmt',
  'auch',
  'die',
  'verpflichtung,',
  'die',
  'erwähnte',
  'terrasse',
  'zwischen',
  'dem',
  'bundesrathause',
  'und',
  'der',
  'vannazhalde',
  'als',
  'öffentliche',
  'anlage',
  'zu',
  'erhalten.'],
 ['3',
  'im',
  'fall',
  'die',
  'schweizerische',
  'eidgenossenschaft',
  'von',
  'der',
  'ihr',
  'durch',
  'artikel',
  '3',
  'eingeräumten',
  'befugnis',
  'zur',
  'beanspruchung',
  'von',
  'land',
  'auf',
  'dem',
  'frühern',
  'territorium',
  'der',
  'kleinen',
  'schanze',
  'gebrauch',
  'machen',
  'würde,',
  'so',
  'übernimmt',
  'überdies',
  'die',
  'einwohnergemeinde',
  'auch',
  'dem',
  'bunde',
  'gegenüber',
  'die',
  'verpflichtung,',
  'die',
  'südlich',
  'von',
  'dem',
  'neu',
  'erstellten',
  'verwaltungsgebäude',
  'verbleibenden',
  'teile',
  'der',
  'kleinen',
  'schanze',
  'als',
  'öffentliche',
  'promenadenanlage',
  'zu',
  'erstellen',
  'und',
  'zu',
  'unterhalten.'],
 ['1',
  'sollte',
  'infolge',
  'förmlichen',
  'beschlusses',
  'der',
  'kompetenten',
  'behörde',
  'das',
  'bundesrathausgebäude',
  'auf',
  'hören,',
  'der',
  'zentralverwaltung',
  'des',
  'bundes',
  'zu',
  'dienen,',
  'so',
  'fallen',
  'die',
  'im',
  'artikel',
  '1',
  'buchstaben',
  'a,',
  'b,',
  'c',
  'bezeichneten',
  'objekte',
  'in',
  'ihrem',
  'dannzumaligen',
  'zustande',
  'als',
  'eigentum',
  'an',
  'die',
  'einwohnergemeinde',
  'bern',
  'zurück',
  'und',
  'erlöschen',
  'die',
  'im',
  'ersten',
  'und',
  'zweiten',
  'absatz',
  'des',
  'artikels',
  '4',
  'seitens',
  'der',
  'einwohnergemeinde',
  'übernommenen',
  'verbindlichkeiten.'],
 ['2',
  'für',
  'den',
  'nämlichen',
  'fall',
  'übernimmt',
  'die',
  'schweizerische',
  'eidgenossenschaft',
  'die',
  'verpflichtung,',
  'der',
  'einwohnergemeinde',
  'bern',
  'die',
  'im',
  'artikel',
  '2',
  'vorgesehene',
  'summe',
  'von',
  '500',
  '000',
  'franken',
  'zurückzuerstatten.'],
 ['infolge',
  'übernahme',
  'der',
  'durch',
  'diese',
  'übereinkunft',
  'festgesetzten',
  'leistungen',
  'der',
  'einwohnergemeinde',
  'bern',
  'erklärt',
  'die',
  'schweizerische',
  'eidgenossenschaft,',
  'dass',
  'dieselbe',
  'den',
  'ihr',
  'durch',
  'bundesbeschlüsse',
  'vom',
  '27.',
  'und',
  '28.',
  'november',
  '18484',
  'auferlegten',
  'verbindlichkeiten',
  'genüge',
  'geleistet',
  'haben',
  'soll,',
  'und',
  'entbindet',
  'die',
  'einwohnergemeinde',
  'bern',
  'vollständig',
  'und',
  'abschliessend',
  'von',
  'jeder',
  'weitern',
  'verpflichtung',
  'und',
  'inanspruchnahme',
  'für',
  'bundessitzleistungen.'],
 ['1',
  'diese',
  'übereinkunft',
  'tritt',
  'nach',
  'allseitiger',
  'endgültiger',
  'ratifikation',
  'in',
  'kraft.'],
 ['2',
  'der',
  'schweizerische',
  'bundesrat',
  'und',
  'der',
  'einwohnergemeinderat',
  'der',
  'stadt',
  'bern',
  'sind',
  'mit',
  'der',
  'vollziehung',
  'derselben',
  'beauftragt.',
  'insbesondere',
  'sollen',
  'alle',
  'diejenigen',
  'bestimmungen,',
  'welche',
  'dingliche',
  'rechte',
  'zum',
  'gegenstand',
  'haben,',
  'nach',
  'mitgabe',
  'der',
  'gesetze',
  'des',
  'kantons',
  'bern',
  'in',
  'rechtsverbindliche',
  'form',
  'gebracht',
  'werden.'],
 ['1',
  'der',
  'bundesfeiertag',
  'ist',
  'ein',
  'den',
  'sonntagen',
  'gleichgestellter',
  'arbeitsfreier',
  'tag.'],
 ['2',
  'er',
  'wird',
  'der',
  'anzahl',
  'der',
  'feiertage',
  'nach',
  'artikel',
  '18',
  'absatz',
  '2',
  'des',
  'arbeitsgesetzes',
  'nicht',
  'angerechnet.'],
 ['3',
  'für',
  'den',
  'arbeitsfreien',
  'bundesfeiertag',
  'besteht',
  'volle',
  'lohnzahlungspflicht',
  'durch',
  'den',
  'arbeitgeber.'],
 ['1',
  'die',
  'beschäftigung',
  'von',
  'arbeitnehmerinnen',
  'und',
  'arbeitnehmern',
  'am',
  'bundesfeiertag',
  'richtet',
  'sich',
  'nach',
  'den',
  'einschlägigen',
  'vorschriften',
  'über',
  'die',
  'sonntagsarbeit.'],
 ['2',
  'wo',
  'keine',
  'gesetzlichen',
  'vorschriften',
  'anwendbar',
  'sind,',
  'können',
  'arbeitnehmerinnen',
  'und',
  'arbeitnehmer',
  'am',
  'bundesfeiertag',
  'beschäftigt',
  'werden,',
  'wenn',
  'es',
  'aus',
  'betrieblichen',
  'gründen',
  'notwendig',
  'ist.',
  'arbeit',
  'bis',
  'zu',
  'fünf',
  'stunden',
  'dauer',
  'ist',
  'durch',
  'freizeit',
  'von',
  'gleicher',
  'dauer,',
  'arbeit',
  'von',
  'mehr',
  'als',
  'fünf',
  'stunden',
  'durch',
  'einen',
  'ersatzruhetag',
  'auszugleichen.'],
 ['vorbehalten',
  'bleiben',
  'die',
  'kantonalen',
  'bestimmungen',
  'über',
  'die',
  'sonntagsruhe',
  'und',
  'die',
  'öffnungszeiten',
  'von',
  'betrieben,',
  'die',
  'dem',
  'detailverkauf,',
  'der',
  'bewirtung',
  'oder',
  'der',
  'unterhaltung',
  'dienen.'],
 ['...'],
 ['1',
  'folgende',
  'organisationen',
  'und',
  'gruppierungen',
  'sind',
  'verboten:a.',
  'die',
  'hamas;',
  'b.',
  'tarn-',
  'und',
  'nachfolgeorganisationen',
  'der',
  'hamas',
  'sowie',
  'organisationen',
  'und',
  'gruppierungen,',
  'die',
  'im',
  'auftrag',
  'oder',
  'im',
  'namen',
  'der',
  'hamas',
  'handeln.'],
 ['2',
  'der',
  'bundesrat',
  'kann',
  'organisationen',
  'und',
  'gruppierungen',
  'verbieten,',
  'deren',
  'führungspersonen,',
  'zielsetzung',
  'oder',
  'mittel',
  'mit',
  'denjenigen',
  'der',
  'hamas',
  'übereinstimmen',
  'und',
  'die',
  'mittelbar',
  'oder',
  'unmittelbar',
  'terroristische',
  'oder',
  'gewalttätig-extremistische',
  'aktivitäten',
  'unterstützen',
  'und',
  'damit',
  'die',
  'innere',
  'oder',
  'äussere',
  'sicherheit',
  'konkret',
  'bedrohen.',
  'er',
  'konsultiert',
  'vorgängig',
  'die',
  'für',
  'die',
  'sicherheitspolitik',
  'zuständigen',
  'kommissionen.',
  'das',
  'verbot',
  'ist',
  'zu',
  'befristen;',
  'es',
  'kann',
  'verlängert',
  'werden.'],
 ['3',
  'die',
  'verbotenen',
  'organisationen',
  'und',
  'gruppierungen',
  'gelten',
  'als',
  'terroristische',
  'organisationen',
  'nach',
  'artikel',
  '260ter',
  'absatz',
  '1',
  'buchstabe',
  'a',
  'ziffer',
  '2',
  'des',
  'strafgesetzbuchs3.'],
 ['die',
  'verfolgung',
  'und',
  'beurteilung',
  'der',
  'beteiligung',
  'an',
  'einer',
  'verbotenen',
  'organisation',
  'oder',
  'gruppierung',
  'und',
  'der',
  'unterstützung',
  'einer',
  'solchen',
  'organisation',
  'oder',
  'gruppierung',
  'unterstehen',
  'der',
  'bundesgerichtsbarkeit.'],
 ['…4'],
 ['1', 'dieses', 'gesetz', 'untersteht', 'dem', 'fakultativen', 'referendum.'],
 ['2', 'der', 'bundesrat', 'bestimmt', 'das', 'inkrafttreten.'],
 ['3',
  'dieses',
  'gesetz',
  'tritt',
  'fünf',
  'jahre',
  'nach',
  'inkrafttreten',
  'ausser',
  'kraft.'],
 ['1',
  'der',
  'kanton',
  'zürich',
  'ist',
  'ein',
  'souveräner',
  'stand',
  'der',
  'schweizerischen',
  'eidgenossenschaft.'],
 ['2',
  'er',
  'gründet',
  'auf',
  'der',
  'eigen-',
  'und',
  'mitverantwortung',
  'seiner',
  'einwohnerinnen',
  'und',
  'einwohner.'],
 ['3',
  'die',
  'staatsgewalt',
  'beruht',
  'auf',
  'dem',
  'volk.',
  'sie',
  'wird',
  'von',
  'den',
  'stimmberechtigten',
  'und',
  'den',
  'behörden',
  'ausgeübt.'],
 ['4',
  'der',
  'kanton',
  'anerkennt',
  'die',
  'selbstständigkeit',
  'der',
  'gemeinden.'],
 ['1',
  'grundlage',
  'und',
  'schranke',
  'staatlichen',
  'handelns',
  'ist',
  'das',
  'recht.'],
 ['2',
  'staatliches',
  'handeln',
  'muss',
  'im',
  'öffentlichen',
  'interesse',
  'liegen',
  'und',
  'verhältnismässig',
  'sein.'],
 ['3',
  'behörden',
  'und',
  'private',
  'handeln',
  'nach',
  'treu',
  'und',
  'glauben.'],
 ['1',
  'der',
  'aufbau',
  'des',
  'staates',
  'und',
  'die',
  'ausübung',
  'staatlicher',
  'macht',
  'beruhen',
  'auf',
  'dem',
  'grundsatz',
  'der',
  'gewaltenteilung.'],
 ['2',
  'niemand',
  'darf',
  'staatliche',
  'macht',
  'unkontrolliert',
  'oder',
  'unbegrenzt',
  'ausüben.'],
 ['der',
  'kanton',
  'arbeitet',
  'mit',
  'den',
  'gemeinden,',
  'den',
  'anderen',
  'kantonen,',
  'dem',
  'bund',
  'und,',
  'in',
  'seinem',
  'zuständigkeitsbereich,',
  'mit',
  'dem',
  'ausland',
  'zusammen.'],
 ['1',
  'jede',
  'person',
  'nimmt',
  'verantwortung',
  'für',
  'sich',
  'selber',
  'wahr',
  'und',
  'trägt',
  'nach',
  'ihren',
  'kräften',
  'zur',
  'bewältigung',
  'der',
  'aufgaben',
  'in',
  'staat',
  'und',
  'gesellschaft',
  'bei.'],
 ['2',
  'der',
  'kanton',
  'und',
  'die',
  'gemeinden',
  'anerkennen',
  'die',
  'initiative',
  'von',
  'einzelnen',
  'und',
  'von',
  'organisationen',
  'zur',
  'förderung',
  'des',
  'gemeinwohls.',
  'sie',
  'fördern',
  'die',
  'hilfe',
  'zur',
  'selbsthilfe.'],
 ['3',
  'sie',
  'nehmen',
  'aufgaben',
  'von',
  'öffentlichem',
  'interesse',
  'wahr,',
  'soweit',
  'private',
  'sie',
  'nicht',
  'angemessen',
  'erfüllen.'],
 ['1',
  'kanton',
  'und',
  'gemeinden',
  'sorgen',
  'für',
  'die',
  'erhaltung',
  'der',
  'lebensgrundlagen.'],
 ['2',
  'in',
  'verantwortung',
  'für',
  'die',
  'kommenden',
  'generationen',
  'sind',
  'sie',
  'einer',
  'ökologisch,',
  'wirtschaftlich',
  'und',
  'sozial',
  'nachhaltigen',
  'entwicklung',
  'verpflichtet.'],
 ['kanton',
  'und',
  'gemeinden',
  'schaffen',
  'günstige',
  'voraussetzungen',
  'für',
  'den',
  'dialog',
  'zwischen',
  'den',
  'kulturen,',
  'weltanschauungen',
  'und',
  'religionen.'],
 ['kanton',
  'und',
  'gemeinden',
  'schaffen',
  'günstige',
  'rahmenbedingungen',
  'für',
  'wirtschaftliche,',
  'kulturelle,',
  'soziale',
  'und',
  'ökologische',
  'innovation.'],
 ['die', 'würde', 'des', 'menschen', 'ist', 'unantastbar.'],
 ['1',
  'die',
  'menschenrechte',
  'und',
  'grundrechte',
  'sind',
  'gemäss',
  'der',
  'bundesverfassung2,',
  'den',
  'für',
  'die',
  'schweiz',
  'verbindlichen',
  'internationalen',
  'abkommen',
  'und',
  'der',
  'kantonsverfassung',
  'gewährleistet.'],
 ['2',
  'die',
  'bestimmungen',
  'der',
  'bundesverfassung',
  'über',
  'die',
  'verwirklichung',
  'und',
  'die',
  'einschränkung',
  'der',
  'grundrechte',
  'gelten',
  'auch',
  'für',
  'die',
  'grundrechte',
  'des',
  'kantonalen',
  'rechts.'],
 ['1', 'alle', 'menschen', 'sind', 'vor', 'dem', 'gesetz', 'gleich.'],
 ['2',
  'niemand',
  'darf',
  'diskriminiert',
  'werden,',
  'namentlich',
  'nicht',
  'wegen',
  'der',
  'herkunft,',
  'der',
  'rasse,',
  'des',
  'geschlechts,',
  'des',
  'alters,',
  'genetischer',
  'merkmale,',
  'der',
  'sprache,',
  'der',
  'sexuellen',
  'orientierung,',
  'der',
  'sozialen',
  'stellung,',
  'der',
  'lebensform,',
  'der',
  'religiösen,',
  'weltanschaulichen',
  'oder',
  'politischen',
  'überzeugung',
  'oder',
  'wegen',
  'einer',
  'körperlichen,',
  'geistigen',
  'oder',
  'psychischen',
  'behinderung.'],
 ['3',
  'mann',
  'und',
  'frau',
  'sind',
  'gleichberechtigt.',
  'sie',
  'haben',
  'anspruch',
  'auf',
  'gleichen',
  'zugang',
  'zu',
  'bildungseinrichtungen',
  'und',
  'ämtern,',
  'auf',
  'gleiche',
  'ausbildung',
  'sowie',
  'auf',
  'gleichen',
  'lohn',
  'für',
  'gleichwertige',
  'arbeit.',
  'kanton',
  'und',
  'gemeinden',
  'fördern',
  'die',
  'tatsächliche',
  'gleichstellung',
  'von',
  'frau',
  'und',
  'mann',
  'in',
  'allen',
  'lebensbereichen.']]

In [8]:
law['text'][0:5].to_list()

['Die Einwohnergemeinde Bern tritt der Schweizerischen Eidgenossenschaft unentgeltlich als Eigentum ab:a. Das Gebäude des Bundesrathauses im roten Quartier der Stadt Bern, mit Nr. 229 bezeichnet, nebst den in demselben enthaltenen Einrichtungen und Mobilien, welche der Einwohnergemeinde angehören, und unter Vorbehalt der im Artikel 62 von der Einwohnergemeinde reservierten Einrichtungen und Gegenstände;\nb. den zwischen den Seitenflügeln des Bundesrathauses und nördlich von dem Mittelbau desselben befindlichen innern Hof von ungefähr 25 000 Quadratfuss Oberfläche.\n Derselbe wird abgetreten bis zu einer in Verlängerung der Nordfassaden der Seitenflügel gezogenen Linie.\n Der in diesem Hofe befindliche Brunnen verbleibt der Einwohnergemeinde, welche denselben in gutem Zustande erhalten und ohne Genehmigung des Bundesrates an dem jetzigen baulichen Zustand mit Inbegriff der Statuen keine Veränderung vornehmen soll.\n Sie wird den Brunnen wie bis anhin mit Wasser versehen.\n Die Eidgenossenschaft verpflichtet sich, den Fortbestand des Brunnens auf ihrem Eigentum als Dienstbarkeit zu übernehmen.\n Der Brunnen sowie der Zugang zu demselben sollen dem Publikum zum angemessenen Hausgebrauch offenstehen.\nc. Eine Parzelle der sogenannten Vannazhalde von ungefähr 7280 Quadratfuss Oberfläche, auf welcher die Eidgenossenschaft ihr Gewächshaus erstellt hat. Ein Plan über die abgetretene Parzelle wird der Übereinkunft beigelegt.\n Die Schweizerische Eidgenossenschaft übernimmt jedoch die Verpflichtung, im Falle der Erbauung einer Strasse längs der Vannazhalde den in beiliegendem Plan gelb angelegten Abschnitt dieser Parzelle der Einwohnergemeinde zum Zwecke des Strassenbaues unentgeltlich wieder abzutreten.\n In diesem Falle ist der Bundesrat berechtigt, im Interesse der räumlichen Verhältnisse des Gewächshauses die Erstellung einer Stützmauer zu verlangen, deren Kosten alsdann zur einen Hälfte die Eidgenossenschaft und zur andern Hälfte die Einwohnergemeinde zu tragen hat.',
 'Die Einwohnergemeinde Bern wird ferner der Schweizerischen Eidgenossenschaft eine Summe von 500 000 Franken in zwischen dem Bundesrate und dem Einwohnergemeinderate zu vereinbarenden Terminen ausbezahlen. Die letzte Ratenzahlung wird jedenfalls spätestens auf Ende tausendachthundertsiebenundsiebenzig fällig.',
 '1 Falls die Schweizerische Eidgenossenschaft zum Zwecke der Erstellung eines von ihr zu benutzenden neuen Verwaltungsgebäudes einen Teil des Bauplatzes zu erwerben wünscht, welcher zwischen der verlängerten Bundesgasse und der neuen Promenade der kleinen Schanze, im Eigentum der Einwohnergemeinde sich befindet, so erklärt sich letztere bereit, der Eidgenossenschaft den nötigen Bauplatz in der verlangten Ausdehnung zum Preise von 10 Franken per Quadratfuss zu übergeben, und zwar am östlichen Ende des oberwähnten Grundeigentums der Einwohnergemeinde, oder wenn die Bemühungen des Einwohnergemeinderates zur Beseitigung der Einspruchsrechte Dritter wider den Bau auf dieser Stelle erfolglos bleiben sollten, am westlichen Ende desselben. In beiden Fällen hat sich die Abtretung auf die ganze 120 Fuss messende Tiefe des Bauplatzes zu erstrecken. Die Einwohnergemeinde ist jedoch zu einer solchen Landabtretung nur verpflichtet, wenn der Bundesrat ein daheriges Begehren innerhalb drei Monaten nach Inkrafttreten dieser Übereinkunft an den Gemeinderat stellt.',
 '2 Durch Anlage des neuen Verwaltungsgebäudes an hier bezeichneter Stelle übernimmt die Eidgenossenschaft bezüglich der Erstellung der Trottoirs und Trottoirsrinnen längs den Strassen, welche an das von ihr erworbene Grundeigentum grenzen, die gleichen Verpflichtungen, welche durch Artikel 5 der Übereinkunft vom 29. Januar 1872 zwischen Staat und Gemeinde Bern den Käufern von Bauparzellen auf dem Territorium des nördlichen Abschnittes der kleinen Schanze überbunden worden sind.',
 '1 Die Einwohnergemeinde Bern übernimmt im fernern die Verpflichtung, auf der ihr gehörenden Vannazhalde keinerlei Gebäude zu errichten, deren Firste die jetzige Höhe der Bundesrathaus-Terrasse überragen würden.']

In [5]:
val.size

30

In [9]:
size = 7
for i in range(0, len(val), size) :
    chunk = val.iloc[i:i+size]
    print(f"i = {i} \n{chunk}, \n")

i = 0
  query_id                                              query  \
0  val_001  May a court lawfully order a three‑month exten...
1  val_002  A claimant holding a national vocational diplo...
2  val_003  A. Rivera, a Peruvian national born in 1994 an...
3  val_004  Mr. Dalton, born in 1941 and resident in a sma...
4  val_005  A parent, separated from their co-parent since...
5  val_006  On 3 March 2012, homeowners Ms. L and her part...
6  val_007  An heirship claims title to a vintage pocket c...

                                      gold_citations
0  Art. 221 Abs. 1 StPO;Art. 140 Abs. 1 StGB;Art....
1  Art. 8 Abs. 1 ATSG;Art. 8 Abs. 1 IVG;Art. 17 A...
2  Art. 29 Abs. 2 BV;Art. 221 Abs. 1 StPO;Art. 39...
3  Art. 505 Abs. 1 ZGB;Art. 467 ZGB;Art. 469 Abs....
4  Art. 133 Abs. 1 ZGB;Art. 133 Abs. 2 ZGB;Art. 2...
5  Art. 1 Abs. 1 OR;Art. 18 Abs. 1 OR;Art. 363 OR...
6  Art. 98 Abs. 2 IPRG;Art. 100 Abs. 1 IPRG;Art. ...  ,

i = 7
  query_id                                              query  \
7  val_008  Has a member of the town council of the Boroug...
8  val_009  A divorced custodial parent lives alone with f...
9  val_010  A Belize-registered investment vehicle (M) aut...

                                      gold_citations
7  Art. 107 Abs. 2 BGG;Art. 333 Abs. 1 StGB;Art. ...
8  Art. 308 Abs. 1 ZGB;Art. 129 Abs. 3 ZGB;Art. 2...
9  Art. 405 Abs. 1 ZPO;Art. 300 ZPO;Art. 397 Abs....  ,

In [ ]:
def regex_retrieve(self) -> list[int]:
    """
    Use extract_and_clean_citations() on the raw query to get citation strings.
    Then look those strings up in corpus['citation'] to get row indices.
    Returns a list of matched row indices (treated as highest-confidence hits).
    If no citations are found in the query, returns an empty list.
    """
    # Call your existing function directly
    citation_strings = extract_and_clean_citations(self.query_text)
 
    if not citation_strings:
            return []
 
    # Match extracted citation strings against the corpus citation column
    # Use str.contains for partial matching (handles "Art. 641 ZGB" matching
    # "Art. 641 Abs. 1 ZGB" in corpus, for example)
    matched_indices = []
    for cit in citation_strings:
        mask = self.corpus["citation"].str.contains(
            cit, case=False, na=False, regex=False
        )
        matched_indices.extend(self.corpus.index[mask].tolist())

    # Deduplicate while preserving order (first match = highest confidence)
    seen = set()
    unique_indices = []
    for idx in matched_indices:
        if idx not in seen:
            seen.add(idx)
            unique_indices.append(idx)

    print(f"Regex found {len(citation_strings)} citation(s) in query "
            f"→ matched {len(unique_indices)} corpus rows.")
    return unique_indices

In [ ]:
def retrieve(self, top_k: int = 10) -> list[dict]:
        """
        Run all three retrievers, fuse with RRF, return top_k results.
 
        Returns
        -------
        List of dicts with keys:
            citation    : str   — from corpus['citation']
            text        : str   — chunk text
            rrf_score   : float — fused score (higher = more relevant)
            rank        : int   — 1 = best
            bm25_rank   : int or None
            faiss_rank  : int or None
            regex_match : bool  — True if this row was found by regex
        """
        try:
            print(f"\nHybrid retrieval (BM25 + FAISS + Regex)")
            print(f"Query: '{self.query_text[:80]}...'")
 
            # ── Step 1: BM25 ──────────────────────────────────────────────────
            # BM25.Best_Match() → np.ndarray of top corpus row-indices
            bm25_indices = self.bm25_retriever.Best_Match()
            bm25_ranked  = bm25_indices.tolist()
 
            # ── Step 2: FAISS ─────────────────────────────────────────────────
            # Faiss.Faiss_retriever() → (scores, indices), shape (n_queries, top_k)
            # Take row 0 — single query
            _, dense_indices_full = self.faiss_retriever.Faiss_retriever()
            faiss_ranked = dense_indices_full[0].tolist()
 
            # ── Step 3: Regex ─────────────────────────────────────────────────
            # extract_and_clean_citations() → citation strings → corpus row indices
            regex_ranked = self._regex_retrieve()
 
            # ── Step 4: Fuse all three with RRF ──────────────────────────────
            # Build the list of ranked lists — only include regex if it found hits.
            # Regex hits go first in the list: they are treated as rank-1 evidence.
            ranked_lists = []
            if regex_ranked:
                ranked_lists.append(regex_ranked)   # highest confidence, goes first
            ranked_lists.append(bm25_ranked)
            ranked_lists.append(faiss_ranked)
 
            rrf_scores = reciprocal_rank_fusion(ranked_lists, k=self.rrf_k)
 
            # ── Step 5: Sort by fused score ───────────────────────────────────
            sorted_candidates = sorted(
                rrf_scores.items(),
                key=lambda x: x[1],
                reverse=True
            )
 
            # ── Step 6: Build rank lookup for diagnostics ─────────────────────
            bm25_rank_lookup  = {idx: r + 1 for r, idx in enumerate(bm25_ranked)}
            faiss_rank_lookup = {idx: r + 1 for r, idx in enumerate(faiss_ranked)}
            regex_match_set   = set(regex_ranked)
 
            # ── Step 7: Build result list ─────────────────────────────────────
            has_citation = "citation" in self.corpus.columns
            results = []
 
            for final_rank, (corpus_idx, score) in enumerate(
                sorted_candidates[:top_k], start=1
            ):
                row = self.corpus.iloc[corpus_idx]
                results.append({
                    "citation":    row["citation"] if has_citation else f"idx_{corpus_idx}",
                    "text":        str(row.get("text", "")),
                    "rrf_score":   round(score, 6),
                    "rank":        final_rank,
                    "bm25_rank":   bm25_rank_lookup.get(corpus_idx),
                    "faiss_rank":  faiss_rank_lookup.get(corpus_idx),
                    "regex_match": corpus_idx in regex_match_set,
                })
 
            regex_hits = sum(1 for r in results if r["regex_match"])
            print(f"Retrieved {len(results)} results | "
                  f"{regex_hits} confirmed by regex | top_k={top_k}")
            return results
 
        except Exception as e:
            raise Agentic_Exception(e, sys) from e
 
def retrieve_as_dataframe(self, top_k: int = 10) -> pd.DataFrame:
    """Same as retrieve() but returns a pandas DataFrame."""
    return pd.DataFrame(self.retrieve(top_k=top_k))

In [9]:
val.index[2]

2

In [ ]:
# ── Main retrieve ─────────────────────────────────────────────────────────

def retrieve(self, top_k: int = 10) -> list[dict]:
    """
    Run all three retrievers, fuse with RRF, return top_k results.

    Returns
    -------
    List of dicts with keys:
        citation    : str   — from corpus['citation']
        text        : str   — chunk text
        rrf_score   : float — fused score (higher = more relevant)
        rank        : int   — 1 = best
        bm25_rank   : int or None
        faiss_rank  : int or None
        regex_match : bool  — True if this row was found by regex
    """
    try:
        print(f"\nHybrid retrieval (BM25 + FAISS + Regex)")
        print(f"Query: '{self.query_text[:80]}...'")

        # ── Step 1: BM25 ──────────────────────────────────────────────────
        # BM25.Best_Match() → np.ndarray of top corpus row-indices
        bm25_indices = self.bm25_retriever.Best_Match()
        bm25_ranked  = bm25_indices.tolist()

        # ── Step 2: FAISS ─────────────────────────────────────────────────
        # Faiss.Faiss_retriever() → (scores, indices), shape (n_queries, top_k)
        # Take row 0 — single query
        _, dense_indices_full = self.faiss_retriever.Faiss_retriever()
        faiss_ranked = dense_indices_full[0].tolist()

        # ── Step 3: Regex ─────────────────────────────────────────────────
        # extract_and_clean_citations() → citation strings → corpus row indices
        regex_ranked = self._regex_retrieve()

        # ── Step 4: Fuse all three with RRF ──────────────────────────────
        # Build the list of ranked lists — only include regex if it found hits.
        # Regex hits go first in the list: they are treated as rank-1 evidence.
        ranked_lists = []
        if regex_ranked:
            ranked_lists.append(regex_ranked)   # highest confidence, goes first
        ranked_lists.append(bm25_ranked)
        ranked_lists.append(faiss_ranked)

        rrf_scores = reciprocal_rank_fusion(ranked_lists, k=self.rrf_k)

        # ── Step 5: Sort by fused score ───────────────────────────────────
        sorted_candidates = sorted(
            rrf_scores.items(),
            key=lambda x: x[1],
            reverse=True
        )

        # ── Step 6: Build rank lookup for diagnostics ─────────────────────
        bm25_rank_lookup  = {idx: r + 1 for r, idx in enumerate(bm25_ranked)}
        faiss_rank_lookup = {idx: r + 1 for r, idx in enumerate(faiss_ranked)}
        regex_match_set   = set(regex_ranked)

        # ── Step 7: Build result list ─────────────────────────────────────
        has_citation = "citation" in self.corpus.columns
        results = []

        for final_rank, (corpus_idx, score) in enumerate(
            sorted_candidates[:top_k], start=1
        ):
            row = self.corpus.iloc[corpus_idx]
            results.append({
                "citation":    row["citation"] if has_citation else f"idx_{corpus_idx}",
                "text":        str(row.get("text", "")),
                "rrf_score":   round(score, 6),
                "rank":        final_rank,
                "bm25_rank":   bm25_rank_lookup.get(corpus_idx),
                "faiss_rank":  faiss_rank_lookup.get(corpus_idx),
                "regex_match": corpus_idx in regex_match_set,
            })

        regex_hits = sum(1 for r in results if r["regex_match"])
        print(f"Retrieved {len(results)} results | "
                f"{regex_hits} confirmed by regex | top_k={top_k}")
        return results

    except Exception as e:
        raise Agentic_Exception(e, sys) from e

def retrieve_as_dataframe(self, top_k: int = 10) -> pd.DataFrame:
    """Same as retrieve() but returns a pandas DataFrame."""
    return pd.DataFrame(self.retrieve(top_k=top_k))

In [1]:
my_dict = {
    1: 100,
    2: 200,
    3: 300,
    4: 400,
    5: 500,
    6: 600,
    7: 700,
    8: 800,
    9: 900,
    10: 1000
}

In [4]:
sort = sorted(my_dict.items(), key=lambda x: x[1])

In [5]:
sort

[(1, 100),
 (2, 200),
 (3, 300),
 (4, 400),
 (5, 500),
 (6, 600),
 (7, 700),
 (8, 800),
 (9, 900),
 (10, 1000)]

In [4]:
law.head()

,citation,text,title
0,Art. 1 112,Die Einwohnergemeinde Bern tritt der Schweizer...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
1,Art. 2 112,Die Einwohnergemeinde Bern wird ferner der Sch...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
2,Art. 3 Abs. 1 112,1 Falls die Schweizerische Eidgenossenschaft z...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
3,Art. 3 Abs. 2 112,2 Durch Anlage des neuen Verwaltungsgebäudes a...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
4,Art. 4 Abs. 1 112,1 Die Einwohnergemeinde Bern übernimmt im fern...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...

In [6]:
law.reset_index(drop=True)

,citation,text,title
0,Art. 1 112,Die Einwohnergemeinde Bern tritt der Schweizer...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
1,Art. 2 112,Die Einwohnergemeinde Bern wird ferner der Sch...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
2,Art. 3 Abs. 1 112,1 Falls die Schweizerische Eidgenossenschaft z...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
3,Art. 3 Abs. 2 112,2 Durch Anlage des neuen Verwaltungsgebäudes a...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
4,Art. 4 Abs. 1 112,1 Die Einwohnergemeinde Bern übernimmt im fern...,Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
...,...,...,...
175928,Art. 9 Abs. 4 ZWV,4 Das Grundbuchamt versieht auf Antrag des Eig...,Zweitwohnungsverordnung vom 4. Dezember 2015 (...
175929,Art. 10 Abs. 1 ZWV,1 Das ARE ist im Bereich des Zweitwohnungswese...,Zweitwohnungsverordnung vom 4. Dezember 2015 (...
175930,Art. 10 Abs. 2 ZWV,2 Die Baubewilligungsbehörden eröffnen dem ARE...,Zweitwohnungsverordnung vom 4. Dezember 2015 (...
175931,Art. 12 ZWV,Die nachstehenden Erlasse werden wie folgt geä...,Zweitwohnungsverordnung vom 4. Dezember 2015 (...
175932,Art. 13 ZWV,Diese Verordnung tritt am 1. Januar 2016 in Kr...,Zweitwohnungsverordnung vom 4. Dezember 2015 (...

In [ ]:
citation = row.get('citation',f'law_idx_{idx}')

In [11]:
law.iloc[5]

citation                                    Art. 4 Abs. 2 112
text        2 Sie übernimmt auch die Verpflichtung, die er...
title       Übereinkunft vom 22. Juni 1875 zwischen dem Sc...
Name: 5, dtype: object

In [12]:
law.iloc[5].get('citation')

'Art. 4 Abs. 2 112'